### ISSUE TITLE
Querying Documentation on supported method translations

### ISSUE THREAD

**Issue by NetMage** [aspnet/EntityFramework.Docs#2015] opened 2019-12-31 19:31 UTC
There seems to be no documentation on what C# methods are supported for query translation e.g. which String methods, which Convert methods, how to access provider canonical functions, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91606b46-d8a2-8824-a1ae-522f35362ec4
* Version Independent ID: 22a92f99-5e43-96d7-82d1-cd02ccdc5af8
* Content: [Querying Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/)
* Content Source: [entity-framework/core/querying/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment] 2019-12-31 19:51
Duplicate of #504

**Closed** 2020-01-02 21:20 UTC
Labels: closed-duplicate
