### ISSUE TITLE
Required and Optional Relationships example

### ISSUE THREAD

**Issue by jraldrin** [aspnet/EntityFramework.Docs#1189] opened 2018-12-21 03:04 UTC
Hi,

The intro to the first "Required and Optional Relationships" example does not state clearly what relationship it is making required. The fluent api can be hard to read just passing around one letter params.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-01 18:13
Duplicate of #1185

**Closed by ajcvickers** 2019-09-01 18:13 UTC
