### ISSUE TITLE
Adding migrations with startup in different project - 

### ISSUE THREAD

**Issue by preshen-goobiah** [aspnet/EntityFramework.Docs#993] opened 2018-09-20 20:31 UTC
Please can support be added for adding migrations with dotnet-ef  when the startup.cs is in a different project to the DbContext. 

https://stackoverflow.com/questions/38705694/add-migration-with-different-assembly helped me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Migrations with Multiple Projects - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2018-09-21 17:06
dotnet ef migrations add --startup-project ./ProjectWithStartup/ --project ./ProjectWithDbContext/

**Comment by bricelam** [comment] 2018-09-21 17:10
The *Using a Separate Project* article is about adding migrations to a project that doesn't contain your `DbContext`. Having `Startup` in a separate project is mentioned a few places throughout the docs.

**Comment by divega** [comment] 2018-09-21 18:18
@bricelam do you think this issue should be closed then?

**Comment by bricelam** [comment] 2018-09-21 19:06
It might be worth mentioning the startup project again on this page.

**Comment by ajcvickers** [comment] 2019-08-29 20:42
Duplicate of ##933

**Closed by ajcvickers** 2019-08-29 20:42 UTC
