### ISSUE TITLE
Raw SQL documentation doesn't answer "what is FromSql()" and isn't very clear

### ISSUE THREAD

**Issue by shiraNadjari** [aspnet/EntityFramework.Docs#1132] opened 2018-11-21 15:01 UTC
i have seen the the raw sql queries articale in microsoft and couldn't understand what Blogs is.
is it the database itself? beacause i tryed and it didnt work.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#including-related-data)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment] 2018-11-26 23:35
The FromSql API allows you to query for entity or query type instances using your own SELECT statements or calls to stored procedures. 

It is somewhat explained in the text of the article, but I get from your post that it isn't clear or explicit enough. 

I also believe the article is difficult to understand due to the Limitations section being the first section.

**Comment by divega** [comment] 2019-01-09 23:23
@weitzhandler the right API to invoke a stored procedure (in this case it is not a function) that doesn't return a result set is dbContext.Database.ExecuteSqlCommand().

**Comment by ajcvickers** [comment] 2019-09-02 19:45
Duplicate of #665

**Closed by ajcvickers** 2019-09-02 19:45 UTC
