### ISSUE TITLE
Document how to exclude a property in an owned type

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/EntityFramework.Docs#1641] opened 2019-08-15 14:19 UTC
How about an example of how to [exclude propert(ies)](https://docs.microsoft.com/en-us/ef/core/modeling/included-properties)?  

I've modified [the sample here](https://github.com/spottedmahn/EntityFramework.Docs/blob/ignore-property/samples/core/Modeling/OwnedEntities/OwnedEntityContext.cs#L48)

reference: https://stackoverflow.com/a/57500971/185123

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by spottedmahn** [comment] 2019-08-15 14:21
Happy to take a stab at updating the doc page once I get the initial go-ahead 😊

**Comment by ajcvickers** [comment] 2019-09-07 21:12
Duplicate of #1457

**Closed by ajcvickers** 2019-09-07 21:12 UTC
Labels: area-aggregates, type-enhancement

**Comment by spottedmahn** [comment] 2019-09-09 14:10
Can we edit #1457 show that it shows up the doc page? 🤔

![image](https://user-images.githubusercontent.com/14079228/64538087-020b8380-d2ea-11e9-8631-a4e8a9036aaa.png)
