### ISSUE TITLE
Error while adding initial migration

### ISSUE THREAD

**Issue by th0mk** [aspnet/EntityFramework.Docs#915] opened 2018-08-13 18:32 UTC
Hi, when creating the initial migration I get this error:

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path '..\aspnetapp\..\aspnetapp\bin\local\Debug\netcoreapp2.1\' because it does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2018-08-13 19:59
@th0mk  I haven't seen that error before. Make sure  you have the latest version of Visual Studio and the .Net Core SDK. 

Clean your project. Exit/restart VS. If that doesn't work - create a new project and see if you get the same error.

**Comment by jurion** [comment] 2018-08-14 13:52
It doesn't show how to use DP and EF outside "controllers". Horrible experience for now working with EF core

**Comment by Rick-Anderson** [comment] 2018-11-13 04:48
@jurion 
>It doesn't show how to use DP and EF outside "controllers".

What is DP? The tutorial has the following a link to [Getting Started with EF Core on .NET Core Console App with a New database](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)

Is that what you were looking for?

@th0mk 	Since I can't reproduce the problem, closing for now. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Closed by Rick-Anderson** 2018-11-13 04:48 UTC
