### ISSUE TITLE
I think it would be good to mention the required namespace(s) here

### ISSUE THREAD

**Issue by drk-mtr** [aspnet/EntityFramework.Docs#848] opened 2018-07-18 18:50 UTC
e.g. `System.ComponentModel.DataAnnotations`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating a Model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2018-07-25 16:59
Duplicate of #729

**Closed by ajcvickers** 2018-07-25 16:59 UTC
