### ISSUE TITLE
Cannot convert lamba expression to type "ServiceLifetime" because it is not a delegate type

### ISSUE THREAD

**Issue by jxc6681** [aspnet/EntityFramework.Docs#1480] opened 2019-05-22 12:05 UTC
I get this error on the line:
services.AddDbContext&lt;BloggingContext&gt;
        (options =&gt; options.UseSqlServer(connection));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio#feedback)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-05-22 19:43
@jxc6681  I'm not sure what you did wrong. Can you following the instructions with a new project?

**Comment by pavolkov** [comment] 2019-07-23 23:38
I have had the same issue. Make sure you have installed "Microsoft.EntityFrameworkCore.SqlServer" NuGet.

**Comment by ajcvickers** [comment] 2019-09-02 17:24
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-02 17:24 UTC
