### ISSUE TITLE
There is an error in Register the context with dependency injection section

### ISSUE THREAD

**Issue by illja96** [aspnet/EntityFramework.Docs#1604] opened 2019-07-26 12:04 UTC
Described that UseSqlServer requires Microsoft.EntityFrameworkCore, but in fact you need to install Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer to use this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio#feedback)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-07-26 16:28
> you need to install `Microsoft.EntityFrameworkCore` and `Microsoft.EntityFrameworkCore.SqlServer` to use this function.


What do you mean install?

**Comment by ajcvickers** [comment] 2019-09-02 18:32
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 18:32 UTC
