### ISSUE TITLE
Edit Details Delete controls

### ISSUE THREAD

**Issue by Jkoross** [aspnet/EntityFramework.Docs#1200] opened 2018-12-26 16:09 UTC
I have followed the above tutorial. My Challenge is on the Edit,Details and Delete controls. When I click on any of them, I get an Http 404 error, no parameter ID is passed and yet my table contains a primary key. I will appreciate your guidance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#reverse-engineer-your-model)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Tuptaju** [comment] 2019-04-08 15:07
I get similar error while working on AdventureWorks database join tables - I can't edit any entry in table CustomerAddresses.

**Comment by ajcvickers** [comment] 2019-09-01 18:17
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 18:17 UTC
