### ISSUE TITLE
bug found on microsoft edge

### ISSUE THREAD

**Issue by mota57** [aspnet/EntityFramework.Docs#1830] opened 2019-10-09 02:10 UTC
I can't visualize the example code's attributes in Microsoft edge, but if I copy the code and paste it in a text editor I can see it.
version 42.17134.1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b143a3f-aecb-49b6-66e1-0c459af0e2de
* Version Independent ID: 1b594bfc-f0a3-4938-a415-50ea34805d8e
* Content: [Data Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types#feedback)
* Content Source: [entity-framework/core/modeling/relational/data-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/data-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by mota57** [comment] 2019-10-09 02:10
Also same happens for the fluent api section.

**Comment by smitpatel** [comment] 2019-10-09 17:02
@mota57 - I am using edge. This is what I see. Are you seeing something different?
![image](https://user-images.githubusercontent.com/1528107/66503332-dfe95a80-ea7b-11e9-88bb-33814398f93d.png)

**Comment by ajcvickers** [comment] 2019-10-18 16:43
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-10-18 16:43 UTC
