### ISSUE TITLE
Setting a value comparer

### ISSUE THREAD

**Issue by Vake93** [aspnet/EntityFramework.Docs#2026] opened 2020-01-05 17:06 UTC
I have a IList&lt;string&gt; coulum with a conversion to json setup. When I create the migration it gives me an warning: 
Microsoft.EntityFrameworkCore.Model.Validation[10620]
      The property 'AvailableProductBrands' on entity type 'Review' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.

I coudn't find any docs on setting a "value comparer" and after trying many things finally came across this https://stackoverflow.com/questions/53050419/json-serialization-value-conversion-not-tracking-changes-with-ef-core , and was able to solve it. Its in builder.Property().Metadata.SetValueComparer. 

Is there any docs on this (SetValueComparers)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#feedback)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-01-06 21:42
Duplicate of #1680

**Closed by ajcvickers** 2020-01-06 21:42 UTC
