### ISSUE TITLE
Reminder that the wizard is not in EF Core

### ISSUE THREAD

**Issue by ThatMouse** [aspnet/EntityFramework.Docs#1505] opened 2019-06-06 14:38 UTC
It might be worth emphasising on this page that the the VS wizard we're used to in EF6 is not available for EF Core and that this is now the only method of generating the EDM. It might save some people from searching for the missing "add" EDM menu in VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by otaconjh** [comment] 2019-08-20 13:35
aspnet-codegenerator can be used can't it?

**Comment by ajcvickers** [comment] 2019-09-02 17:39
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 17:39 UTC
