### ISSUE TITLE
Reference instructions are backwards

### ISSUE THREAD

**Issue by aleksandrjPersonal** [aspnet/EntityFramework.Docs#1242] opened 2019-01-18 18:40 UTC
Add a project reference from the Blogging.Migrations.Startup project to the Blogging.Model project. 
This is backwards. 
You need to add the ref from Blogging.Model to the Blogging.Migrations.Startup or else you get: Error	NU1201	Project Blogging.Migrations.Startup is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project Blogging.Migrations.Startup supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)	Blogging.Model	C:\Users\******\Blogging.Model\Blogging.Model.csproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by sbeaudoin** [comment] 2019-02-09 01:01
What is the role of the console application "Migration.Startup"?  This project is created but not mentioned anywhere else on this document.  I did the initial "add-migration" and no code at all is created in this project.  Surely, I am missing something, but I think this something should be mentioned on this document.

**Comment by Heidelberger** [comment] 2019-07-28 05:54
I had the same issue.  Reversing the reference as stated here fixes the problem.

Current instruction (incorrect):
Add a project reference from the Blogging.Migrations.Startup project to the Blogging.Model project.

Please update to:
Add a project reference from the Blogging.Model project to the Blogging.Migrations.Startup project.

**Comment by ajcvickers** [comment] 2019-09-01 18:50
Duplicate of #933

**Closed by ajcvickers** 2019-09-01 18:50 UTC
Labels: help wanted
