### ISSUE TITLE
Show how to use function mappings

### ISSUE THREAD

**Issue by chaim1221** [aspnet/EntityFramework.Docs#1134] opened 2018-11-22 07:42 UTC
There is no example anywhere of how to use these!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ff4787-97f3-7dd4-5d94-98c2025c8645
* Version Independent ID: 0b755bb0-b557-0029-4c24-9fa7ec6ec822
* Content: [EF.Functions Property (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.functions?view=efcore-2.1#Microsoft_EntityFrameworkCore_EF_Functions)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EF.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by jrummell** [comment] 2018-12-11 15:10
An example would be great

**Comment by jrummell** [comment] 2018-12-11 15:13
It looks like you can do something like this:

query.Where(e => EF.Functions.DateDiffDay(e.BidRequiredBy, DateTime.UtcNow) == days)

**Comment by ajcvickers** [comment] 2019-09-07 20:19
Duplicate of #500

**Closed by ajcvickers** 2019-09-07 20:19 UTC
Labels: area-query, type-enhancement
