### ISSUE TITLE
will these instructions work for Mac?

### ISSUE THREAD

**Issue by softchris** [aspnet/EntityFramework.Docs#1515] opened 2019-06-09 20:22 UTC
My guess is that we need to add instructions pointing to a sql lite usage as shown on this page?  https://medium.com/@yostane/entity-framework-core-and-sqlite-getting-started-on-macos-and-visual-studio-code-27f3830db77c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment] 2019-06-10 21:07
@softchris thanks for looking into how this content can be improved!

Note that for better or for worse, the "Installing Entity Framework Core" page isn't exactly structured as a tutorial. It kind of assumes the reader has some knowledge of working on .NET Core on your environment, so it does not delve into what IDE or EF Core provider you will likely want to use on any given OS. It rather tries to focus on what packages you will have add to your project. 

Unfortunately, there is still a lot of information in it about different variations. And for what it's worth, a lot of that information won't be true about EF Core 3.0. 

The rest of the topics under "Get Started" follow a tutorial format, much like that blog post. Perhaps a separate tutorial specific about how to use EF Core on a Mac would help, not sure. 

In summary, the constrains are:
- There is a lot of information to convey across lots of dimensions (e.g. EF Core version, OS, application type, IDE/CLI, data provider)
- There are a few tools we can use to separate those dimensions, like separate pages, tabs (only used in [a few of the tutorials](https://docs.microsoft.com/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio)), and documentation versioning (the drop down at the top of the ToC that [some use](https://docs.microsoft.com/powershell/scripting/overview?view=powershell-6), but that we don't have in this repo)
- If you try to put all the information that may be relevant in a page, it will likely become very complex
- We have a relative small budget :smile:

I am happy to brainstorm if there is a different way we could organize things that would lead to a better outcome.

**Comment by softchris** [comment] 2019-06-13 03:23
appreciate the lengthy response.. Happy to brainstorm :).. I think what might help is a quickstart section for different scenarios. Lots of good contents for sure in these docs I just find it hard to start with a simple hello world = 1) install needed package 2) define a db context class with a few entities in there, create a connection , query etc.. also very happy to dedicate time to make this happen :)

**Comment by softchris** [comment] 2019-06-13 03:31
I just realized you have that but it's under Get Started > .NET Core > New Database. I expected a structure like this https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-quickstart-create-templates-use-the-portal with a 'Quickstart' section. I've seen that structure in a lot of our docs. I also love this format https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function with images and a sense of completion at the bottom.. But yea let's brainstorm and see how I can be of help :)

**Comment by ajcvickers** [comment] 2019-09-02 17:46
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 17:46 UTC
