### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by AlexandriaBoxCrush** [aspnet/EntityFramework.Docs#1624] opened 2019-08-05 17:08 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

I keep getting this unhandled Exception while working on your example linked below:
https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database

If you could help me to learn to handle this exception that would be dandy.

**Comment by ajcvickers** [comment] 2019-09-02 18:39
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 18:39 UTC
