### ISSUE TITLE
Emphasize importance of using LocalDB instead of your system instance of SQL Server

### ISSUE THREAD

**Issue by gregfra** [aspnet/EntityFramework.Docs#1148] opened 2018-12-02 02:54 UTC
Current walkthrough instructions work correctly on your installed version of SQL Server, from Express on up (e.g. .\MSSQLSERVER or .\SQLEXPRESS). You can create databases and EF linking code with no problems, as long as you have the server configuration of your user login with RW privileges. But when navigating to /Blogs under "Run the application", IIS Express tries to connect to your full system instance of SQL Server and most likely won't have the required permissions for Windows Authentication, and in that case the server will emit a SQLException with a "login failed" message. The LocalDB server "(localDB)\mssqllocaldb" must be used in this walkthrough. Further reading on LocalDB: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-08-29 23:26
@gregfra Are you saying LocalDB must be used because other databases might be configured in ways that don't work?

**Comment by gregfra** [comment] 2019-08-30 01:30
@ajcvickers That's right. Out of the box my SQL Server Express has limited access privileges and apparently so does IIS Express. 

In the "Create your database" step of the walkthrough, if you improvise in the fourth bullet point and use a real SQL Server DB with RW privileges, database creation works. You don't learn about the execution problem until the last step of the walkthrough. For this particular walkthrough, LocalDB is guaranteed to work throughout.

**Comment by ErikEJ** [comment] 2019-08-30 06:51
Normally you have full access to SQL Server Express on your own machine.

**Comment by ajcvickers** [comment] 2019-08-30 21:16
@gregfra Thanks for the additional info.

**Comment by AndySmiffy** [comment] 2019-09-05 13:03
Amending the startup.cs code to
var connection = @"Server=.\sqlexpress;Database=Blogging;Trusted_Connection=True;ConnectRetryCount=0";
worked for me - I'm running a local instance of sqlexpressl, hence the dot rather than the local server name in the connection string. - Plus my db name is different, obviously (Blogging).

**Comment by smitpatel** [comment] 2019-09-30 18:49
Duplicate of #1091 
We don't want to do anything more than that. If the connectionstring in our sample is not something your system is configured with then you should update it to something more suitable.

**Closed by smitpatel** 2019-09-30 18:49 UTC
