### ISSUE TITLE
Navigation properties in DbQuery

### ISSUE THREAD

**Issue by drinkbird** [aspnet/EntityFramework.Docs#950] opened 2018-08-29 09:19 UTC
In model-first `DbSet`s the database structure is generated to fit the navigation properties defined on the entity models.

On the other hand, according to documentation, a `DbView` model has to match a view that already exists and is not generated by EF.

What I couldn't find in the documentation is how to create navigation properties in a `DbView` model, along with an example on how to support that navigation when creating the view in the database.

Thanks

**Comment by ajcvickers** [comment] 2019-08-29 20:24
Duplicate of #809

**Closed by ajcvickers** 2019-08-29 20:24 UTC
