### ISSUE TITLE
Discuss .NETStandard libraraies

### ISSUE THREAD

**Issue by bendono** [aspnet/EntityFramework.Docs#1230] opened 2019-01-11 07:47 UTC
While following this tutorial, I tried to make a few minor changes and was met with confusing errors. Much of this frustration could have been avoided if this tutorial included (or linked to) a few more details.

Specifically, I wanted to keep my EF model in a separate .NET Standard project. However, the CLI commands do not work in this scenario. With a bit of searching, I was able to determine a workaround:
-Add a .Net Core console application or .Net Framework application.
-Use the --startup-project &lt;..\&lt;console app&gt; parameter for both ef migrations add ef database update commands.

While searching, this seems to be a common pain point for other EF developers. A tutorial of course cannot cover all scenarios, but a little more details or even a link to such details would go a long way in getting more people started faster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ajcvickers** [comment] 2019-09-01 18:36
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 18:36 UTC
