### ISSUE TITLE
CustomAnnotationProvider

### ISSUE THREAD

**Issue by btodts** [aspnet/EntityFramework.Docs#1032] opened 2018-10-05 07:41 UTC
Might be worth mentioning that, when you want to access Annotations in the SqlGenerator, you need to replace the `SqlServerMigrationsAnnotationProvider` with a custom Provider, as explained here: https://github.com/aspnet/EntityFrameworkCore/issues/10258#issuecomment-343605538.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by chernihiv** [comment] 2018-10-08 13:41
I'd like to know how we can Inject service inside MyMigrationsSqlGenerator, e.g.
class MyMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
{
    public MyMigrationsSqlGenerator(
        IMyCustomService service
        MigrationsSqlGeneratorDependencies dependencies,
        IMigrationsAnnotationProvider migrationsAnnotations)
        : base(dependencies, migrationsAnnotations)  { }

    ....
}

it throws an exception
Unable to resolve service for type 'IMyCustomService' while attempting to activate 'MyMigrationsSqlGenerator'

**Comment by btodts** [comment] 2018-10-08 13:45
@chernihiv I think you'd better create a separate issue in the [EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) repository for this.

**Comment by ajcvickers** [comment] 2019-08-29 21:17
Duplicate of #599

**Closed by ajcvickers** 2019-08-29 21:17 UTC
