### ISSUE TITLE
sample code throws an error

### ISSUE THREAD

**Issue by jfraschilla** [aspnet/EntityFramework.Docs#1206] opened 2018-12-29 01:18 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

The sample code for GetStarted/NetCore/ConsoleApp.SQLite throws an exception.  Using VS2017 Community Edition

**Comment by ajcvickers** [comment] 2019-09-01 18:18
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 18:18 UTC
