### ISSUE TITLE
Need a ConsoleApp example with Connection Strings

### ISSUE THREAD

**Issue by kae36** [aspnet/EntityFramework.Docs#1344] opened 2019-03-08 20:01 UTC
It would be nice to have an .net core 2.2 example of a windows console application using MS SQL Server connection strings. There doesn't seem to be any that I can find. console apps don't seem to use Startup, so some example for main would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings#feedback)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Going-Gone** [comment] 2019-04-11 17:06
You can use a json file to store the strings, and reference them there.

**Comment by kae36** [comment] 2019-04-12 00:14
There are several examples of the JSON file format and db connection strings. There are also examples of code used in a Web Application to initialize the DbContext from the connection strings in the JSON file, but there are no examples of how to initialize a DbContext used in a Console Application. It would just be nice to have an example.

**Comment by LinchaiTheShinigami** [comment] 2019-04-18 22:57
I tried using the example provided under the DotNet Framework example to create a console application.

But I am obtaining a NullReferenceException on the Configuration Manager when running the command:
`PM> dotnet.exe ef migrations add StudentDatabase`

Stack Trace:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at CreateDatabaseModels.AssetContext.ConfigSettings() in E:\CodeProgramming\C#\Projects\HelloSQLServerDatabase\CreateDatabaseModels\Program.cs:line 50
   at CreateDatabaseModels.AssetContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in E:\CodeProgramming\C#\Projects\HelloSQLServerDatabase\CreateDatabaseModels\Program.cs:line 57
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.`

`using Microsoft.EntityFrameworkCore;
using System;
using System.Configuration;

namespace CreateDatabaseModels
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.ReadKey();
        }
    }

    public class AssetContext:DbContext
    {
        public DbSet<EntityDataModel.Students> Students { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["test"].ConnectionString); **//This is where it goes wrong!**
            }
        }

    }
}

//In a separate file
using System;
using System.ComponentModel.DataAnnotations;
namespace CreateDatabaseModels.EntityDataModel
{
    public class Students
    {
        [Key] public int StudentId { get; set; }
        public int Marks { get; set; }
    }
}

//In app.config file
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="setting" value="value"/>
  </appSettings>
  <connectionStrings>
    <add name="test" connectionString="Server=localhost;Database=StudentDatabase;Trusted_Connection=True"/>
  </connectionStrings>
</configuration>`

**Comment by montwell** [comment] 2019-05-15 20:51
This was my solution.

`using Microsoft.Extensions.Configuration;
using System;
using System.IO;

namespace example
{
    public interface IConfigurationManager
    {
        string ConnectionStrings(string connectionString);
    }

    class ConfigurationManager : IConfigurationManager
    {
        private static Lazy<ConfigurationManager> instance = new Lazy<ConfigurationManager>(() => new ConfigurationManager());

        public static ConfigurationManager Instance => instance.Value;

        private readonly IConfigurationRoot configuration;

        private ConfigurationManager()
        {
            IConfigurationBuilder configurationBuilder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);

            configuration = configurationBuilder.Build();
        }

        public string ConnectionStrings(string connectionString)
        {
            return configuration.GetConnectionString(connectionString);
        }
    }
}`

**Comment by LinchaiTheShinigami** [comment] 2019-05-15 21:00
@montwell - So you need to create your own implementation of IConfigurationManager so that the migration can read the contents of a config file?

**Comment by montwell** [comment] 2019-05-15 21:04
Well it seems like in all the examples given you would need to load the appsettings.json in the context that you were using it.  Then you would need to pass those parameters along through the entirety of your program.  This seemed like the best way to be able to access the file throughout a complex program.

**Comment by ajcvickers** [comment] 2019-09-01 21:07
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 21:07 UTC

**Comment by dchase-sir** [comment] 2020-09-30 17:59
I went to the duplicate 481 and didn't find any reference to documentation being created to address this, I am having the same issue, I am creating a .NET Core console application, and want to move the connection string out of the Context.cs. So far it looks like I need to basically make my own config file and just read it. The code to read such file is not in the Context.cs and I'm having trouble getting it to acknowledge the existence of the variable in another part of the program. 

All of this just to move the connection string, which the link in the file does not address console apps at all - everything is for Web, which has internal wirings setup for you. I've spent a week now looking at how DI works in .NET core (basically answering every other question I've never asked), the entire time thinking I'm missing something or in the wrong part of the internet again.

Any help on where this documentation exists would be helpful, but please don't refer me to generic DI or ASP.NET Core Web documentation as the mechanism is granted ahead of time in that environment.

**Comment by ajcvickers** [comment] 2020-09-30 18:16
@dchase-sir There is no code in EF Core to read configuration from a file. You can choose to use whatever mechanism you feel is appropriate in your code to store and read the connection string, and then pass that value to `UseSqlServer` or equivalent. This could be the .NET Core configuration system that ASP.NET Core uses, but it could also be a simple text file, and anything else you choose.

**Comment by dchase-sir** [comment] 2020-09-30 18:19
Aj, Thank you - any tips on making that available to the DbContext? I tried setting the connection string as a public static variable in Program.cs (there is no Startup.cs, and if I add one the constructor does not get called), but it still couldn't see the public static variable even though it's in the same namespace. If I use DI, do I just use AddService/etc from Main? I appreciate your response it's a breath of fresh air regardless!

**Comment by ajcvickers** [comment] 2020-09-30 18:23
@dchase-sir I typically don't use D.I. in a console application, so I just want to be able to use `new` to create a DbContext instance. If I have the connection string available at that time, then a pattern like this works well:

```C#
public class SomeDbContext : DbContext
{
    private readonly string _connectionString;

    public SomeDbContext(string connectionString)
    {
        _connectionString = connectionString;
    }
   
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(_connectionString);
}
```

**Comment by dchase-sir** [comment] 2020-09-30 18:31
I just experienced a moment of clarity when I realized that in my program, I can just new the context like I did in EF6 and that the constructor in the Context with DbContextOptions is irrelevant in my scenario unless I choose to make it more complex. 

Thank you!
