### ISSUE TITLE
Supported .NET implementations should be updated for 3.0

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework.Docs#1663] opened 2019-08-21 23:46 UTC
.NET Framework is not supported anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7cee01-ae77-571c-5517-8037428a2277
* Version Independent ID: 832b8636-b005-c397-dbb4-0ad7f9c0b43d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/platforms/)
* Content Source: [entity-framework/core/platforms/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/platforms/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-07 20:25
Duplicate of #1635

**Closed by ajcvickers** 2019-09-07 20:25 UTC
Labels: area-getting-started, type-correctness
