### ISSUE TITLE
Concurrency info for applying migrations at runtime

### ISSUE THREAD

**Issue by nphmuller** [aspnet/EntityFramework.Docs#1310] opened 2019-02-25 13:53 UTC
Applying migrations at runtime seems like a fine solution for me, but I wonder what would happen if my application runs on multiple nodes. Basically, what happens when I run multiple runtime migrations at the same time? Is this scenario supported?

Either way, it would be nice if it's documented. Either as a warning or as an assurance.

For (custom) data seeding this is already documented a bit (https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding#custom-initialization-logic).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#apply-migrations-at-runtime)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2019-09-01 20:22
Duplicate of #814

**Closed by ajcvickers** 2019-09-01 20:22 UTC
