### ISSUE TITLE
Scaffold-DbContext with Fluent API

### ISSUE THREAD

**Issue by peteralbanese** [aspnet/EntityFramework.Docs#1187] opened 2018-12-21 00:53 UTC
Suggestion: It would be nice if when you ran Scaffold-DbContext command, you could supply a switch to use Fluent API and an Entity Map directory. For example, --UseFluentApi --FluentDirectory MyEntityMaps. Each entity would have their own entity map file in the FluentDirectory specified. This would result in less pollution of the OnModelCreating(ModelBuilder modelBuilder) method in the DbContext Class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2018-12-21 18:22
Dupe of aspnet/EntityFrameworkCore#8434?

**Closed** 2019-09-01 18:10 UTC
