### ISSUE TITLE
myDbContext.Database.Migrate();

### ISSUE THREAD

**Issue by harshaghanta** [aspnet/EntityFramework.Docs#1996] opened 2019-12-18 04:07 UTC
migrate method is  accessible only when using below snippet
myDbContext.GetInfrastructure().GetService&lt;IMigrator&gt;()
and is not accessible with the below line.
myDbContext.Database.Migrate();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2019-12-18 22:39
@harshaghanta Please post a small, runnable project that demonstrates this is not working so that we can investigate.

**Comment by ajcvickers** [comment] 2020-01-03 00:51
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-01-03 00:51 UTC

**Comment by IGx89** [comment] 2020-01-22 17:39
It's there, but you need to ensure your project references Microsoft.EntityFrameworkCore.Relational and your source file contains `using Microsoft.EntityFrameworkCore;` -- it's an extension method. Visual Studio did not have a quick fix when I first tried using it so I briefly thought it was missing as well.
