### ISSUE TITLE
Small clarification suggestion

### ISSUE THREAD

**Issue by EKanadily** [aspnet/EntityFramework.Docs#1522] opened 2019-06-15 08:09 UTC
in the article it says "Cascade means dependent entities are also deleted" ,i would change that to "Cascade means when the principal entity get deleted Entity framework will also delete dependent entities"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:51
Duplicate of #473

**Closed by ajcvickers** 2019-09-02 17:51 UTC
