### ISSUE TITLE
There's a [Key] annotation

### ISSUE THREAD

**Issue by zidocread** [aspnet/EntityFramework.Docs#1233] opened 2019-01-14 20:26 UTC
The docs need updating, according to the tutorial there is an annotation for PK
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio#create-the-officeassignment-entity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a38fe8f-c674-0673-a13f-b87a7a9edf78
* Version Independent ID: fad97301-bb2b-f974-bf1c-c80c9d143b3d
* Content: [Primary Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/primary-keys)
* Content Source: [entity-framework/core/modeling/relational/primary-keys.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/primary-keys.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-01-14 20:45
@zidocread See https://docs.microsoft.com/en-us/ef/core/modeling/keys

**Comment by ajcvickers** [comment] 2019-01-14 21:34
@divega The separation of core and relational topics does seem to trip people up...

**Comment by divega** [comment] 2019-01-14 22:43
Probably we can make things more discoverable by by:

1. Renaming the core topic to "Primary Keys" from the current "Keys (primary)"
2. Renaming the relational topic to "Primary Key Constraint"
3. Adding pointers to the first one on the latter, and text clarifying that what relational allows configuring (the name of the primary key constraint) is in addition to the things you can always configure on primary keys.

**Comment by gusmally** [comment] 2019-01-18 18:16
It tripped me up too. The summary for the Relational Database Modeling page (https://docs.microsoft.com/en-us/ef/core/modeling/relational/) makes it sound like core topics are included (or at least, it doesn't specifically say they are excluded)

**Comment by ajcvickers** [comment] 2019-09-01 18:40
Duplicate of #862

**Closed by ajcvickers** 2019-09-01 18:40 UTC
