### ISSUE TITLE
Provide step by step example, not just scaffolding

### ISSUE THREAD

**Issue by trondhindenes** [aspnet/EntityFramework.Docs#1609] opened 2019-07-30 18:05 UTC
Scaffolding is extremely brittle in .net, leaving me unable to actually see the code needed to use EF Core in a controller. Please update this example with actual code examples instead of relying on the (super-buggy) codegen/scaffolding tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-07-30 18:36
In what way is it brittle? We've found it robust. Consider following [Razor Pages with Entity Framework Core in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)

**Comment by Rick-Anderson** [comment] 2019-07-30 18:37
Or the MVC version of that tutorial. The RP version has better queries and is more up to date.

**Comment by trondhindenes** [comment] 2019-07-31 08:55
I'm not able to make it work on Linux and found enough open github issues on the subject to decide it was not worth the effort.

**Comment by trondhindenes** [comment] 2019-07-31 08:56
> The RP version
What is "RP"?

**Comment by Rick-Anderson** [comment] 2019-07-31 14:51
Razor Pages

**Comment by ajcvickers** [comment] 2019-09-02 18:34
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 18:34 UTC
