### ISSUE TITLE
Error with Add-Migration InitialCreate

### ISSUE THREAD

**Issue by lackovic** [aspnet/EntityFramework.Docs#766] opened 2018-06-14 12:50 UTC
When I run "Add-Migration InitialCreate" I get the error:
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path '...\Project.sfproj\bin\Debug\' because it does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ajcvickers** [comment] 2018-06-14 16:21
@lackovic Is the file really an "sfproj" or is that a typo?

**Comment by ajcvickers** [comment] 2018-06-18 19:27
Triage: looks like a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/10327

@lackovic If this is still failing with EF Core 2.1, then please file a new issue including a runnable project/solution at https://github.com/aspnet/EntityFrameworkCore/issues

**Closed by ajcvickers** 2018-06-18 19:27 UTC
