### ISSUE TITLE
Show transaction where FK is dependant

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/EntityFramework.Docs#2016] opened 2020-01-01 13:07 UTC
Please demo how to do a transaction when add data to table A first to get a primary key, then to table B where TableAId is the foreign key to table A's primary key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-01-03 00:54
@VR-Architect It's pretty unusual to do this--normally EF handles propagation of FK values as needed when `SaveChanges` is used. Can you provide some more details on why you want to do this explicitly, and why this would make a good example?

**Comment by ajcvickers** [comment] 2020-01-10 18:25
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-01-10 18:25 UTC
