### ISSUE TITLE
Add an example for model building with fluent API and Actions

### ISSUE THREAD

**Issue by matteocontrini** [aspnet/EntityFramework.Docs#1790] opened 2019-09-30 18:36 UTC
This page currently has an example that looks like this:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>()
        .Property(b => b.Url)
        .IsRequired();
}
```

It would be nice if it also mentioned the alternative syntax, which helps better organizing code:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    builder.Entity<Blog>(ConfigureBlogEntity);
}

private void ConfigureBlogEntity(EntityTypeBuilder<Blog> builder)
{
    builder.Entity<Blog>()
        .Property(b => b.Url)
        .IsRequired();
}
```

I couldn't actually find this way of configuring entities in the docs at all (I might have missed it), so this seems a good place to mention it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437af67-630b-d28f-7fbd-3eedf647f22a
* Version Independent ID: 6c44f987-19a7-c256-e8fa-10378e61cf6e
* Content: [Creating and configuring a model - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/#feedback)
* Content Source: [entity-framework/core/modeling/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by jahbenjah** [comment] 2019-10-02 15:06
@matteocontrini
I think this is a great feature and the command `dotnet ef dbcontext scaffold` must have **an option to scaffold a DbContext and entity types in this way**. Actually, after scaffolding a real database you end with `OnModelCreating` method with high cyclomatic complexity, a low maintenance index and a massive number of lines.

**Comment by ajcvickers** [comment] 2019-10-09 17:28
Duplicate of #411. Also, see https://github.com/aspnet/EntityFrameworkCore/issues/8434

**Closed by ajcvickers** 2019-10-09 17:28 UTC
