### ISSUE TITLE
Special names of CreateWebHostBuilder  and CreateHostBuilder

### ISSUE THREAD

**Issue by guardrex** [aspnet/EntityFramework.Docs#1465] opened 2019-05-11 11:59 UTC
Hello - I'm working on https://github.com/aspnet/AspNetCore.Docs/issues/12383 in the aspnet/AspNetCore.Docs, and I don't see that you call out the special builder method names for Web Host and Generic Host over here (for migrations to work properly). We'll have coverage for it on our side if you prefer that we carry it. Since you have a page for ASP.NET Core tho, this would be a possible spot for a note on it over here, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9100ee43-8270-8e27-c82c-e7735d3921ea
* Version Independent ID: f48e3e18-09f3-4455-756d-5c3ff04c1629
* Content: [Getting Started on ASP.NET Core - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/)
* Content Source: [entity-framework/core/get-started/aspnetcore/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:12
Duplicate of #1464

**Closed by ajcvickers** 2019-09-02 17:12 UTC
