### ISSUE TITLE
Document Migrations at a conceptual level

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#507] opened 2017-10-06 17:32 UTC
Issue #506 is about how to use the command line tools, but we also need better documentation on why and how to use Migrations at the conceptual level.

**Comment by bricelam** [comment] 2017-11-07 16:48
This issue is a subset of #204

**Comment by bricelam** [comment] 2017-11-10 23:00
Duplicate of #204

**Closed by bricelam** 2017-11-10 23:00 UTC
