### ISSUE TITLE
Effect on the where clause?

### ISSUE THREAD

**Issue by ndc** [aspnet/EntityFramework.Docs#1649] opened 2019-08-19 01:57 UTC
So how marking a property as a concurrency token change the where clause of the query?
Would love to see examples and comparison between no token and with token.
Is it possible to mark multiple properties as concurrency token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency#feedback)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 18:50
Duplicate of #492

**Closed by ajcvickers** 2019-09-02 18:50 UTC
