### ISSUE TITLE
dotnet tool install --global dotnet-ef doesnt seem to work with .NET Core 3.1

### ISSUE THREAD

**Issue by ihorbond** [aspnet/EntityFramework.Docs#2044] opened 2020-01-10 22:29 UTC
I needed to run db scaffolding so I came here to find "dotnet tool install --global dotnet-ef" command but it failed with error "Tool 'dotnet-ef' failed to install..." Running dotnet --version results in 3.1.100. So I ran "dotnet tool install --global dotnet-ef --version 3.1" and now dotnet-ef installed successfully. Not sure if this is something on my end or anyone else is experiencing this issue ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2020-01-14 00:08
@ihorbond I see no reason why the first command should fail while the second one succeeded. If you can provide full details of your system, including what is installed, and attach a project where this error happens, then we will investigate.

**Comment by Rick-Anderson** [comment] 2020-01-15 23:07
@ihorbond  closing. If you can provide more information we can reopen this issue.

**Closed by Rick-Anderson** 2020-01-15 23:07 UTC

**Comment by zliang68** [comment] 2020-02-14 02:46
I have installed DotNet Core SDK 3.1.101 on Windows 10 Pro
This command won't work: 
-> dotnet tool install --global dotnet-ef
error NU1100: Unable to resolve 'dotnet-ef ' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'dotnet-ef ' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by TylerOdenthal** [comment] 2020-04-17 17:14
I'm getting the same response when installing LUISGen

```
C:\Users\Tyler\Desktop\ChatWorks>dotnet tool install -g LUISGen
error NU1100: Unable to resolve 'luisgen (>= 0.0.0)' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'luisgen (>= 0.0.0)' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'luisgen' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

**Comment by Hartur** [comment] 2020-05-09 14:05
Try specify the version of dotnet-ef. It worked for me;
`dotnet tool install --global dotnet-ef --version 3.0.0`

**Comment by VuyisaM** [comment] 2020-06-11 21:20
Hi I am getting the same error and I used 3.1.3

**Comment by mbrookson** [comment] 2020-11-20 22:09
Recently had the same issue installing the latest version for .NET 5.

As suggested above, being explicit with the version also fixed my issue.

`dotnet tool install --global dotnet-ef --version 3.1.3`

**Comment by salmento** [comment] 2021-04-17 15:47
I trying to run this command, but it's not working. I've tried many solution but nothing yet.

 dotnet tool install --global dotnet-ef --version 6.0.0-preview.2.21154.2
C:\Users\user\AppData\Local\Temp\umaqxw14.mph\restore.csproj : error NU1100: Unable to resolve 'dotnet-ef (>= 6.0.0-preview.2.21154.2)' for 'net6.0'.
C:\Users\user\AppData\Local\Temp\umaqxw14.mph\restore.csproj : error NU1100: Unable to resolve 'dotnet-ef (>= 6.0.0-preview.2.21154.2)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.       
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by salmento** [comment] 2021-04-17 16:34
I solved the issue indicating the source at the end of the command


 **dotnet tool install --global dotnet-ef --version 6.0.0-preview.2.21154.2 --add-source https://api.nuget.org/v3/index.json**

**Comment by vormc2005** [comment] 2021-04-17 17:57
Adding source worked dotnet tool install --global dotnet-ef --version 5.0.0 --add-source https://api.nuget.org/v3/index.json

**Comment by Rick-Anderson** [comment] 2021-04-18 01:46
If you've installed prerelease versions you need to run
` dotnet tool uninstall --global dotnet-ef` first

**Comment by ivanko337** [comment] 2021-05-01 19:56
> 
> 
> I solved the issue indicating the source at the end of the command
> 
> **dotnet tool install --global dotnet-ef --version 6.0.0-preview.2.21154.2 --add-source https://api.nuget.org/v3/index.json**

Thanks! That works in for me!

**Comment by Anas-Alhariri** [comment] 2021-05-11 00:51
None of them worked for me.

`.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download`

**Here is the error:**
`The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool`

**Comment by Anas-Alhariri** [comment] 2021-05-11 01:43
> @Anas-Alhariri try removing it before installing.

It didn't work either, I have tried to remove it locally and globally, but actually, it is not installed.
I was working on a project on my Mac and just downloaded it from Github again on my Windows 10 PC to continue working with multiple monitors.

My working environment is a fresh Windows 10 installation in a virtual machine everything seems to operate perfectly except for the dotnet-ef tool. I could run the project and communicate with my API and the Database, but after I have made additional classes and tried to update the migrations and the database I got the error.

I don't think I have dotnet-ef ever installed (globally nor locally) on this system.

Any ideas?

**Comment by Anas-Alhariri** [comment] 2021-05-11 04:13
**I have fixed it!!**

The problem is with the source of the package. The original default sources seem to be corrupted.
I tried to add `https://api.nuget.org/v3/index.json` as a source and re-run the installation but still didn't work, even tho the source is enabled as a package source!

I found an option that will ignore failed sources and continue to try downloading and installing the package in `dotnet tool `command line.

**### Here is how I fixed it:**
**Run these lines in order.**
**_NOTE:_**
_**----- NOT SURE IF THIS NECESSARY, please try without it and if didn't work try again from step one and include this line. -----**_

1. `dotnet nuget add source https://api.nuget.org/v3/index.json -n DefaultNuget`
2. `dotnet nuget locals -c all `
3. make sure your new source has been added and enabled successfully, it should be the last item in the list: `dotnet nuget list source`
4. Now, run the following command and make sure to use the dotnet-ef version that matches your SDK version: `dotnet tool install -g dotnet-ef --version 5.0.5 --ignore-failed-sources`
5. Finally, you should receive a message in your terminal/commandline like the following: ```
**You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '5.0.5') was successfully installed.**
```
6. That means you have successfully installed the dotnet-ef.
7. To confirm the installation again, you could use: `**dotnet-ef**` and the output should look something like this:

`
                     _/\__
               ---==/    \\
         ___  ___   |.    \|\
        | __|| __|  |  )   \\\
        | _| | _|   \_/ |  //|\\
        |___||_|       /   \\\/\\
Entity Framework Core .NET Command-line Tools 5.0.5

Usage: dotnet ef [options] [command]

Options:
  --version        Show version information
  -h|--help        Show help information
  -v|--verbose     Show verbose output.
  --no-color       Don't colorize output.
  --prefix-output  Prefix output with level.

Commands:
  dbcontext   Commands to manage DbContext types.
  migrations  Commands to manage migrations.

Use "dotnet ef [command] --help" for more information about a command.`



That's all 👍

**Comment by Anas-Alhariri** [comment] 2021-05-11 04:59
> dotnet nuget locals --clear all

Thank you for your reply.
I agree with you, but that for some reason didn't fix the issue for me.

**Comment by Rick-Anderson** [comment] 2021-05-11 05:11
@Anas-Alhariri thanks for reporting back and I'm glad you got it working. I'll watch this issue to see if others have the same problem.

**Comment by Anas-Alhariri** [comment] 2021-05-13 00:48
> @Anas-Alhariri thanks for reporting back and I'm glad you got it working. I'll watch this issue to see if others have the same problem.

I found the source of the issue.
I forgot that I have added the nuget lib source in my Visual Studio for package downloading. It seems like mistakenly I missed copying the link and pasting it correctly. After changing that to the correct link, things went smooth and as expected.

Thank you Rick for your help :)

**Comment by PavithraMadhushini** [comment] 2021-05-20 07:36
I cant install `dotnet tool install --global dotnet-ef` in VS Code project terminal.

`dotnet tool install --global dotnet-ef`
C:\Program Files\dotnet\sdk\5.0.203\NuGet.targets(131,5): error : Failed to download package 'dotnet-ef.5.0.6' from 'https://www.nuget.org/api/v2/package/dotnet-ef/5.0.6'. [C:\Users\Pawithra\AppData\Local\Temp\qv2qgydb.smr\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.203\NuGet.targets(131,5): error : The SSL connection could not be established, see inner exception. [C:\Users\Pawithra\AppData\Local\Temp\qv2qgydb.smr\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.203\NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\Users\Pawithra\AppData\Local\Temp\qv2qgydb.smr\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.203\NuGet.targets(131,5): error : The feed 'nuget.org [https://www.nuget.org/api/v2/]' lists package 'dotnet-ef.5.0.6' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [C:\Users\Pawithra\AppData\Local\Temp\qv2qgydb.smr\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.203\NuGet.targets(131,5): error :   Unable to find package 'dotnet-ef.5.0.6'. [C:\Users\Pawithra\AppData\Local\Temp\qv2qgydb.smr\restore.csproj]
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sefatanam** [comment] 2021-06-29 18:47
> **I have fixed it!!**
> 
> The problem is with the source of the package. The original default sources seem to be corrupted.
> I tried to add `https://api.nuget.org/v3/index.json` as a source and re-run the installation but still didn't work, even tho the source is enabled as a package source!
> 
> I found an option that will ignore failed sources and continue to try downloading and installing the package in `dotnet tool `command line.
> 
> **### Here is how I fixed it:**
> **Run these lines in order.**
> **_NOTE:_**
> _**----- NOT SURE IF THIS NECESSARY, please try without it and if didn't work try again from step one and include step 2. -----**_
> 
> 1. `dotnet nuget add source https://api.nuget.org/v3/index.json -n DefaultNuget`
> 2. `dotnet nuget locals -c all `
> 3. make sure your new source has been added and enabled successfully, it should be the last item in the list: `dotnet nuget list source`
> 4. Now, run the following command and make sure to use the dotnet-ef version that matches your SDK version: `dotnet tool install -g dotnet-ef --version 5.0.5 --ignore-failed-sources`
> 5. Finally, you should receive a message in your terminal/commandline like the following:
> 
> ```
> You can invoke the tool using the following command: dotnet-ef
> Tool dotnet-ef (version '5.0.5') was successfully installed.
> ```
> 
> 1. That means you have successfully installed the `dotnet-ef`.
> 2. To confirm the installation again, you could use: **`dotnet-ef`** and the output should look something like this:
> 
> ```
>                      _/\__
>                ---==/    \\
>          ___  ___   |.    \|\
>         | __|| __|  |  )   \\\
>         | _| | _|   \_/ |  //|\\
>         |___||_|       /   \\\/\\
> Entity Framework Core .NET Command-line Tools 5.0.5
> 
> Usage: dotnet ef [options] [command]
> 
> Options:
>   --version        Show version information
>   -h|--help        Show help information
>   -v|--verbose     Show verbose output.
>   --no-color       Don't colorize output.
>   --prefix-output  Prefix output with level.
> 
> Commands:
>   dbcontext   Commands to manage DbContext types.
>   migrations  Commands to manage migrations.
> 
> Use "dotnet ef [command] --help" for more information about a command.
> ```
> 
> That's all 👍

that's really works on my machine . Thanks a lot.

**Comment by Anas-Alhariri** [comment] 2021-06-29 19:03
> > **I have fixed it!!**
> > The problem is with the source of the package. The original default sources seem to be corrupted.
> > I tried to add `https://api.nuget.org/v3/index.json` as a source and re-run the installation but still didn't work, even tho the source is enabled as a package source!
> > I found an option that will ignore failed sources and continue to try downloading and installing the package in `dotnet tool `command line.
> > **### Here is how I fixed it:**
> > **Run these lines in order.**
> > **_NOTE:_**
> > _**----- NOT SURE IF THIS NECESSARY, please try without it and if didn't work try again from step one and include step 2. -----**_
> > 
> > 1. `dotnet nuget add source https://api.nuget.org/v3/index.json -n DefaultNuget`
> > 2. `dotnet nuget locals -c all `
> > 3. make sure your new source has been added and enabled successfully, it should be the last item in the list: `dotnet nuget list source`
> > 4. Now, run the following command and make sure to use the dotnet-ef version that matches your SDK version: `dotnet tool install -g dotnet-ef --version 5.0.5 --ignore-failed-sources`
> > 5. Finally, you should receive a message in your terminal/commandline like the following:
> > 
> > ```
> > You can invoke the tool using the following command: dotnet-ef
> > Tool dotnet-ef (version '5.0.5') was successfully installed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. That means you have successfully installed the `dotnet-ef`.
> > 2. To confirm the installation again, you could use: **`dotnet-ef`** and the output should look something like this:
> > 
> > ```
> >                      _/\__
> >                ---==/    \\
> >          ___  ___   |.    \|\
> >         | __|| __|  |  )   \\\
> >         | _| | _|   \_/ |  //|\\
> >         |___||_|       /   \\\/\\
> > Entity Framework Core .NET Command-line Tools 5.0.5
> > 
> > Usage: dotnet ef [options] [command]
> > 
> > Options:
> >   --version        Show version information
> >   -h|--help        Show help information
> >   -v|--verbose     Show verbose output.
> >   --no-color       Don't colorize output.
> >   --prefix-output  Prefix output with level.
> > 
> > Commands:
> >   dbcontext   Commands to manage DbContext types.
> >   migrations  Commands to manage migrations.
> > 
> > Use "dotnet ef [command] --help" for more information about a command.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's all 👍
> 
> that's really works on my machine . Thanks a lot.

My pleasure😊 glad I was honored to be able to help 👍🏼

**Comment by Enough7** [comment] 2021-07-15 12:37
`dotnet tool install -g dotnet-ef --ignore-failed-sources` did the thing for me thanks @Anas-Alhariri

**Comment by RodrigoGroener** [comment] 2021-09-01 11:41
`dotnet nuget list source` returned an empty list.
I guess you only run into this problem when you install `dotnet` **without** **having visual studio** installed on your machnie that pre populates the official nuget site as source.

running `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` fixed the issue for me.

**Comment by Anas-Alhariri** [comment] 2021-09-01 17:29
> `dotnet nuget list source` returned an empty list.
> I guess you only run into this problem when you install `dotnet` **without** **having visual studio** installed on your machnie that pre populates the official nuget site as source.
> 
> running `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` fixed the issue for me.

**I agree**

**Comment by coldcanuk** [comment] 2021-12-05 04:02
> 4\. dotnet tool install -g dotnet-ef --version 5.0.5 --ignore-failed-sources

These steps worked perfect! Thank you!
I swear I had VS Code installed first.. but I must have d/l and installed dotnet before and just didn't clue in. 

Cheers

**Comment by hashimabbaz** [comment] 2023-01-06 17:20
I used dotnet tool update --no-cache dotnet-ef --version 7.0.1 --ignore-failed-sources. By using --no-cache option, it replaced the dotnet 5.0.2 cache which was causing the issue.

**Comment by datwayskrt** [comment] 2023-03-21 21:29
This worked for me:

1. `dotnet tool uninstall --global dotnet-ef`
2. `dotnet tool install --global dotnet-ef`
3. set the env
4. restart visual studio
