### ISSUE TITLE
Document different ways to map functions

### ISSUE THREAD

**Issue by RichardD2** [aspnet/EntityFramework.Docs#1600] opened 2019-07-25 15:25 UTC
The "more information" link does not provide more information about this method. It points to a generic "Creating a model" page, which doesn't seem to contain anything relating to DB functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379880e3-69de-11aa-4ded-14ee4e8b8b62
* Version Independent ID: 1fd40a1b-fb81-9695-7b7b-ad10c6394aa1
* Content: [DbFunctionBuilder.HasTranslation(Func&lt;IReadOnlyCollection&lt;Expression&gt;,Expression&gt;) Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.dbfunctionbuilder.hastranslation?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/DbFunctionBuilder.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/DbFunctionBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-07 20:19
Duplicate of #500

**Closed by ajcvickers** 2019-09-07 20:19 UTC
Labels: area-entity-mapping, type-enhancement
