### ISSUE TITLE
DbQuery<T> for unit testing

### ISSUE THREAD

**Issue by aaronhudon** [aspnet/EntityFramework.Docs#948] opened 2018-08-27 22:57 UTC
An example on how to construct a DbQuery&lt;T&gt; for unit testing would be most appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by fscyr** [comment] 2019-01-31 06:39
_context.Query<QueryTypeClass>.FromSql<QueryTypeClass>("select * from table1");

**Comment by oleg-orlenko** [comment] 2019-03-08 13:03
Any input on this ?

**Comment by aaronhudon** [comment] 2019-03-08 17:57
@oleg-orlenko Zero feedback on this.  Either:
- Switch to DbSet<T>.  This is unfortunate because you'll be required to define a primary key
- Hold your breath and don't unit test database views :-/

**Comment by oleg-orlenko** [comment] 2019-03-09 07:30
@aaronhudon thx for reply. I solved this with mocked context and DbQuery<Etty> from
https://github.com/huysentruitw/entity-framework-core-mock

**Comment by ajcvickers** [comment] 2019-08-29 20:22
Duplicate of #898

**Closed by ajcvickers** 2019-08-29 20:22 UTC
