### ISSUE TITLE
Show an example for .Net Core other than ASP.Net Core

### ISSUE THREAD

**Issue by RowlandShaw** [aspnet/EntityFramework.Docs#1040] opened 2018-10-08 08:14 UTC
There are examples for .Net Classic which is app.config happy, and ASP.Net core which talks about appsettings.json as a ASP.Net Core configuration system, but the case for .net Core console apps is plain absent (nor any pointer to a relevant place to look, for those migrating from the classic platforms...)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-gb/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by dyslexicanaboko** [comment] 2018-11-02 00:42
I feel your pain: https://blog.bitscry.com/2017/05/30/appsettings-json-in-net-core-console-app/

**Comment by bigtfromaz** [comment] 2018-11-04 23:12
Ditto

**Comment by RowlandShaw** [comment] 2018-11-05 21:20
I was thinking more the what to do with the configuration, having come from EF6 that happily goes looking for the DefaultConnection in the app.config's configuration settings without having to think about it

**Comment by spivonious** [comment] 2018-12-18 16:48
@bigtfromaz - I think best practice would be to pass in any needed configuration as parameters and not rely on app.config/appsettings.json.

**Comment by roji** [comment] 2019-04-10 18:04
@divega it seems that a small sample for a .NET Core console application with a Microsoft.Extensions.Configuration could make sense, as well as a small note on why hard-coding the connection string is unadvisable. Note also #1344 which seems to be a dup of this.

**Comment by roji** [comment] 2019-04-10 18:07
There seem to be other requests on the same page for other types of connection strings (e.g. non-LocalDB, Azure...). As brief section pointing users to the right pages could help.

**Comment by divega** [comment] 2019-04-11 07:19
@roji from what I am reading in the comments from @bigtfromaz and @RowlandShaw, this issue was motivated by how the new configuration system doesn’t have a global static entry point that you can access from everywhere but you rather need to pass around an IConfiguration directly or via de DI container. I.e. the main scenario mentioned is how to flow the application’s connection string into a .NET Standard library. 

This is a concern that we have seen before, and it is product of a conscious design trade off. It is actually a bit orthogonal to EF Core, but a sample of how to flow the connection string using EF Core or Microsoft.Configuration.Extensions abstractions would probably help. 

I agree that having a page linking to the right way to configure for different data sources would help. It kinds of exist already in the providers page, but perhaps it can be improved, or the docs of the providers that it links to can be improved (most of them, we don’t own though).

**Comment by ajcvickers** [comment] 2019-09-06 22:27
Dupe of #481

**Closed by ajcvickers** 2019-09-06 22:27 UTC
Labels: area-getting-started, punted-for-2.2, type-enhancement
