### ISSUE TITLE
Linux does not support Trusted_Connection from a container.  Show other examples.

### ISSUE THREAD

**Issue by Vaccano** [aspnet/EntityFramework.Docs#1797] opened 2019-10-01 22:28 UTC
All these examples use Trusted_connection.  But if you are running on a Linux container you cannot have a "trusted connection" (because it cannot join the domain and gMSAs are not supported on Linux).  

It would be good to have an example or two that used the username and password option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment] 2019-10-03 03:48
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/867

**Closed by AndriySvyryd** 2019-10-03 03:48 UTC
