### ISSUE TITLE
Include tip explaining what package is required for the code snippets

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1423] opened 2019-04-11 06:54 UTC
Like https://github.com/aspnet/EntityFramework.Docs/pull/1408.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7b56f-7f91-2f15-1fb6-4f481e97534f
* Version Independent ID: 6d9c65c6-f159-b234-48fd-f25da05f0f32
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sqlite.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 16:39
Duplicate of #740

**Closed by ajcvickers** 2019-09-02 16:39 UTC
