### ISSUE TITLE
Build Failed at the "Create the initial migration" step

### ISSUE THREAD

**Issue by johnny-sayasane** [aspnet/EntityFramework.Docs#1093] opened 2018-11-01 17:08 UTC
I did exactly the same as this tutorial but I found this in the Error List:
Error	NU1201	Project Blogging.Migrations.Startup is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project Blogging.Migrations.Startup supports: netcoreaSeverity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Blogging.Migrations.Startup is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project Blogging.Migrations.Startup supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)	Blogging.Model	C:\Users\johnn\source\repos\Blogging\Blogging.Model\Blogging.Model.csproj	1	
pp2.1(.NETCoreApp,Version=v2.1)	Blogging.Model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by KurtVerbrugge** [comment] 2018-11-29 13:41
I have the same issue - help would be appriciated

**Comment by thebigdavetheory** [comment] 2018-12-22 08:31
I had this problem, but got it to build with a small change to the Add-Migration command in package manager.

Note: I'm Using  DotNetCore v2.2, and the EF-Core version matches (v2.2)

There are two ways to do this the one I used is the first...
Method #1:
a.)Go into Package Manager Console in VS.
b.) Set the "Default project" to your model project "Blogging.Model"
c.) Run the following command

Add-Migration InitialCreate -StartupProject Blogging.Migrations.Startup

this works because it will use the default project you selected to find the DbContext, and the Startup Project to run the commands.

Method 2: 
Type the command:
Add-Migration -Project Blogging.Model -StartupProject Blogging.Migrations.Startup

this should combine all the concepts from method 1 into a single command line, and it shouldn't matter whats selected as the default project in the Package Manager Console.

**Comment by mnuess** [comment] 2018-12-23 23:10
I have the same issue. Altough I ensured my "Default project" is set to "Blogging.Model".

So unfortunately none of your methods worked for me.

**Comment by liquidboy** [comment] 2019-01-18 22:45
i can't get this working .. like others i think the referencing is wrong or running into .net standard 2 vs .netcoreapp 3 issues ...  Please fix these samples

**Comment by akuma06** [comment] 2019-01-20 20:37
@liquidboy Please refer to the solution from this issue https://github.com/aspnet/EntityFramework.Docs/issues/1242

**Comment by ajcvickers** [comment] 2019-08-29 21:57
Duplicate of #933

**Closed by ajcvickers** 2019-08-29 21:57 UTC
