### ISSUE TITLE
Explain how keyless types can be used to execute raw SQL query for "non-entities"

### ISSUE THREAD

**Issue by Mart-Bogdan** [aspnet/EntityFramework.Docs#969] opened 2018-09-08 15:00 UTC
In EF6 there were method to call raw sql for non entity https://docs.microsoft.com/en-us/ef/ef6/querying/raw-sql#writing-sql-queries-for-non-entity-types

It's seems impossible in EF Core, and RelationalDatabaseFacadeExtensions.ExecuteSqlCommand  (eg context.Database.ExecuteSqlCommand  ) don't allow selects, only non-query statements.

Should I create new DbSet for non entity dynamically? or other workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Mart-Bogdan** [comment] 2018-09-08 15:04
It this `Context.Query<KnowlageNodeRecurcive>().FromSql(" XXXX ").ToListAsync();` valid way of doing this?

**Comment by Mart-Bogdan** [comment] 2018-09-13 15:48
@ajcvickers @Paul-Dempsey   it's seems improper way.

I'm getting "Cannot create a DbSet for 'KnowlageNodeRecurcive' because this type is not included in the model for the context."

If data type not registered in context, as table.

Perhaps there are no way to use this, and we should be stuck with raw ADO SqlCommand. :-(

**Comment by ajcvickers** [comment] 2018-09-13 16:04
@Mart-Bogdan See https://github.com/aspnet/EntityFrameworkCore/issues/1862 and https://github.com/aspnet/EntityFrameworkCore/issues/10753

**Comment by Mart-Bogdan** [comment] 2018-09-13 17:01
@ajcvickers thank you so much!!! It helped.

I've added `builder.Query<..>`  into **OnModelCreating**. 

For other who would be interested and would be reading this thread.

P.S. should this issue be opened? It's related to updating documentation.

**Comment by odahcam** [comment] 2018-12-06 19:15
I'm getting an Exception: 

```
An exception of type 'System.MissingMethodException' occurred in Havan.MinhaHavan.Infra.dll but was not handled in user code: 'Method not found: 'System.Linq.IQueryable`1<!!0> Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSql(System.Linq.IQueryable`1<!!0>, System.String, System.Object[])'.'
```

But I have no idea of what that means. 😕

**Comment by weitzhandler** [comment] 2018-12-24 10:02
This is wrong. You should be able to execute raw SQL without return types, or by getting the result directly if the functions are of primitive type.
Create a wrapper and an entity type for each `bit`-typed function doesn't make sense.

**Comment by odahcam** [comment] 2018-12-24 17:55
I totally agree, to get my raw query working I had to make configurations on `OnModelCreating` hook and create models and it feels totally wrong.

**Comment by weitzhandler** [comment] 2018-12-24 21:57
Here's how you can achieve this:

    public static async Task<T> ExecuteScalarAsync<T>(this DbContext context, string rawSql,
      params object[] parameters)
    {
      var conn = context.Database.GetDbConnection();
      using (var command = conn.CreateCommand())
      {
        command.CommandText = rawSql;
        if (parameters != null)
          foreach (var p in parameters)
            command.Parameters.Add(p);
        await conn.OpenAsync();
        return (T)await command.ExecuteScalarAsync();
      }
    }

**Comment by ajcvickers** [comment] 2019-09-07 20:39
Duplicate of #410

**Closed by ajcvickers** 2019-09-07 20:39 UTC
Labels: area-query-raw, type-enhancement

**Comment by kobruleht** [comment] 2021-01-16 20:38
Tried to use weitzhandler  code in ASP.NET MVC Core 5 with npgsql.

Line
 command.Parameters.Add(p);

throws error

ArgumentNullException: Value cannot be null. (Parameter 'value')
Npgsql.NpgsqlParameterCollection.Add(NpgsqlParameter value)

How to fox this code so that parameters with null values are also accepted ?

**Comment by Mart-Bogdan** [comment] 2021-01-16 20:56
@kobruleht , you can't pass nulls to SqlParameters. Use DbNull.Instance or something like that.

**Comment by kobruleht** [comment] 2021-01-16 21:04
Should if statement added which passes DbNull in parameter is null ?

I posted it also in https://stackoverflow.com/questions/65754699/get-value-from-sql-select-if-parameter-may-be-null

**Comment by Mart-Bogdan** [comment] 2021-01-16 21:07
You could use ?? Operator to replace values with DbNull

But better to use EF method, it would convert nulls, and would be able to map back to classes

**Comment by kobruleht** [comment] 2021-01-16 21:15
I need to run arbitrary sql queries  which can return  string, decimal?, bool? and other scalar values. There is no EF class for result. How to use EF method for this ?  Like

```
var total = ctx.ExecuteScalar<decimal?>(@"select ... where p1={0}", null);

var res = ctx.ExecuteScalar<string>(@"select ... where p1={0}", null);

```
I found some code which injects keyless type dynamically to DbContext in OnModelCreated method. Maybe this can used if EF method is better.

**Comment by kobruleht** [comment] 2021-01-16 21:29
I changed 

`                    command.Parameters.Add(p);
`

to

`                    command.Parameters.Add(p ?? DBNull.Value);
`
but got exception

```
InvalidCastException: The value "" is not of type "NpgsqlParameter" and cannot be used in this parameter collection.
Npgsql.NpgsqlParameterCollection.Cast(object value)
```

**Comment by KushAlayaCare** [comment] 2021-09-09 08:36
> Here's how you can achieve this:
> 
> ```
> public static async Task<T> ExecuteScalarAsync<T>(this DbContext context, string rawSql,
>   params object[] parameters)
> {
>   var conn = context.Database.GetDbConnection();
>   using (var command = conn.CreateCommand())
>   {
>     command.CommandText = rawSql;
>     if (parameters != null)
>       foreach (var p in parameters)
>         command.Parameters.Add(p);
>     await conn.OpenAsync();
>     return (T)await command.ExecuteScalarAsync();
>   }
> }                                                         
> ```

this does not support something like List<T> as a return type?

**Comment by kobruleht** [comment] 2021-09-09 09:12
I dont need List resturn type. Tried your code as:

```
        public async Task<T> ExecScalarAsync<T>(string rawSql, params object[] parameters)
        {
            var conn = Database.GetDbConnection();
            using var command = conn.CreateCommand();
            command.CommandText = rawSql;
            if (parameters != null)
                foreach (var p in parameters)
                    command.Parameters.Add(p);
            // https://stackoverflow.com/questions/57645042/net-core-ef-cleaning-up-sqlconnection-createcommand
            //EF Core internally does that when processing commands which need open connection -open it at the beginning, close it when done.Except if it was opened externally, in which case they do nothing.
            bool wasOpen = command.Connection.State == ConnectionState.Open;
            if (!wasOpen) await command.Connection.OpenAsync();
            try
            {
                var res = await command.ExecuteScalarAsync();
                if (res == DBNull.Value || res == null)
                    return default;
                return (T)res;
            }
            finally
            {
                if (!wasOpen) command.Connection.Close();
            }

        }

But got exception:

``` The value "LV" is not of type "NpgsqlParameter" and cannot be used in this parameter collection.
System.InvalidCastException: The value "LV" is not of type "NpgsqlParameter" and cannot be used in this parameter collection.
   at Npgsql.NpgsqlParameterCollection.Cast(Object value)
   at Npgsql.NpgsqlParameterCollection.Add(Object value)
   at MyApp.ExecScalarAsync[T](String rawSql, Object[] parameters) ...
