### ISSUE TITLE
Have DbContext Dependency Injection available in Class library project. Is it possible?

### ISSUE THREAD

**Issue by topgun743** [aspnet/EntityFramework.Docs#1067] opened 2018-10-22 14:55 UTC
In an Asp.Net Core MVC based application, we know that Dependency Injection (DI) is defined right in _Startup_ class under _ConfigureServices_ method like so:

```
var connection = @"Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;ConnectRetryCount=0";
services.AddDbContext<BloggingContext>(options => options.UseSqlServer(connection));

```
And then we can make use of this DI in Controller via constructor like so:

```
public class BlogsController : Controller
{
    private readonly BloggingContext _context;

    public BlogsController(BloggingContext context)
    {
        _context = context;
    }

    // GET: Blogs
    public async Task<IActionResult> Index()
    {
        return View(await _context.Blog.ToListAsync());
    }
}

```

But in a real project in order to achieve separation of concerns, we make use of Business Logic Layer (BLL) and create separate project for it. Similarly there is also a Data Abstraction Layer (DAL) which contains all the stuff needed to communicate with the backend Database.

   1. So in our case can we access this Dependency Injection in BLL like so ?
```
public class MyClassLib
{
    private readonly BloggingContext _context;

    public MyClassLib(BloggingContext context)
    {
        _context = context;
    }
}
```
2. Also we need to do scaffolding against an existing database and as such _DbContext_ class will be created in DAL project. _OnConfiguring_ method will be defined in this created _DbContext_ class. Here connection string is hard coded in class.

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
     if (!optionsBuilder.IsConfigured)
     {
         optionsBuilder.UseSqlServer("Server=.;Database=TestDB;user id=sa;password=abcxyz");
     }
}
```

But can we declare Connection string in our main UI MVC project in some .json or .config file and access this same connection string in DAL with in our DbContext class? 
Asking it because this way this DAL project could be accessed by various other projects in solution.

This same question asked on Stackoverflow:
https://stackoverflow.com/questions/52834316/have-dbcontext-dependency-injection-available-in-class-library-project-is-it-po/52834695#52834695

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47bf610-692d-9d40-d85f-aec1e2a87a07
* Version Independent ID: 3c94634a-4b17-bc13-7436-0c61aea03ab6
* Content: [Configuring a DbContext - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext)
* Content Source: [entity-framework/core/miscellaneous/configuring-dbcontext.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/configuring-dbcontext.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by WAlvarezV** [comment] 2019-07-19 19:02
I have a project, whit DDD structure and I define the connection string in the secrets json or can be I  the app settings.jason

**Comment by ajcvickers** [comment] 2019-08-29 21:43
@topgun743 
> But can we declare Connection string in our main UI MVC project in some .json or .config file and access this same connection string in DAL with in our DbContext class?

Yes. What issues are you running into doing this?

**Comment by ajcvickers** [comment] 2019-09-06 19:42
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-06 19:42 UTC
