### ISSUE TITLE
toString alternate

### ISSUE THREAD

**Issue by Sakthi7692** [aspnet/EntityFramework.Docs#2042] opened 2020-01-10 10:40 UTC
is there any alternate way to handle the tostring...

```C#
            //ProductId is Int
            // ==> db.Products.Where(p=>p.ProductId.ToString().Contains("p"))
            //to check for the 2 in the 29, we require this kind of query
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#feedback)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @smitpatel
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-01-11 21:46
@Sakthi7692 Please provide more details about what it is you're attempting to do. Posting a small, runnable project that demonstrates the issue you are having is often the best way for us to be able to help.

**Comment by ajcvickers** [comment] 2020-01-21 17:15
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2020-01-21 17:15 UTC
