### ISSUE TITLE
Outdated document?

### ISSUE THREAD

**Issue by pantonis** [aspnet/EntityFramework.Docs#1355] opened 2019-03-13 18:19 UTC
Documentation for [relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships date is from 2016.Is it outdated?

This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues
****

**Comment by roji** [comment] 2019-04-10 17:55
@pantonis although that page hasn't been updated in a while, it is the latest version that exists. Note that changes have been made to other, related pages (e.g. [owned entity types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)).

Is there any specific subject which you think is missing from the relationship page?

**Comment by ajcvickers** [comment] 2019-09-01 21:13
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-01 21:13 UTC
