### ISSUE TITLE
NuGet package Microsoft.EntityFrameworkCore.Relational also required

### ISSUE THREAD

**Issue by ElwinAP** [aspnet/EntityFramework.Docs#1057] opened 2018-10-16 09:10 UTC
If working in a project with only Microsoft.EntityFrameworkCore package installed, you'll also need Microsoft.EntityFrameworkCore.Relational installed for ToTable to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eaa7354-52ca-e66f-eeae-0bb35dafa2fe
* Version Independent ID: 92283a0b-6c68-59a0-f4f3-557b3a4b28b3
* Content: [Table Mapping - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/tables)
* Content Source: [entity-framework/core/modeling/relational/tables.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/tables.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-08-29 21:28
Duplicate of #1056

**Closed by ajcvickers** 2019-08-29 21:28 UTC
Labels: help wanted
