### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'

### ISSUE THREAD

**Issue by harvinders** [aspnet/EntityFramework.Docs#1500] opened 2019-06-02 23:53 UTC
The call to `db.Database.Migrate();` fails with the SQLite error. Not sure why this should be happening. 

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var dbPath = "data2.db";
            optionsBuilder.UseSqlite($"Data source={dbPath}");
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started#feedback)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:39
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 17:39 UTC
