### ISSUE TITLE
Database first approach pluralizing entity names

### ISSUE THREAD

**Issue by laksh-parab** [aspnet/EntityFramework.Docs#255] opened 2016-09-02 04:12 UTC
I am trying to use database first approach based on article [here](https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/platforms/aspnetcore/existing-db.rst) however after the running command below , scaffolding is creating pluralized entity names.

`Scaffold-DbContext "Server=(local);Database=MyDatabase;Trusted_Connection=True;"Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities`

The issue was also posted on SO [here](http://stackoverflow.com/questions/39281647/entityframework-core-database-first-approach-pluralizing-table-names)

**Comment by bricelam** [comment] 2016-09-02 16:29
Dupe of aspnet/EntityFramework#3060. Until that is implemented, the entity type names are taken verbatim from the table names.

**Closed by bricelam** 2016-09-02 16:29 UTC
