### ISSUE TITLE
DeleteBehavior.Cascade with required or optional relationship shows incorrect output

### ISSUE THREAD

**Issue by collinstevens** [aspnet/EntityFramework.Docs#1603] opened 2019-07-26 06:30 UTC
The section with title [DeleteBehavior.Cascade with required or optional relationship](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete#deletebehaviorcascade-with-required-or-optional-relationship-1) shows incorrect output.

```
After loading entities:
    Blog '1' is in state Unchanged with 2 posts referenced.
      Post '1' is in state Unchanged with FK '1' and reference to blog '1'.
      Post '2' is in state Unchanged with FK '1' and reference to blog '1'.

  After making posts orphans:
    Blog '1' is in state Unchanged with 2 posts referenced.
      Post '1' is in state Modified with FK '1' and no reference to a blog.
      Post '2' is in state Modified with FK '1' and no reference to a blog.

  Saving changes:
    DELETE FROM [Posts] WHERE [PostId] = 1
    DELETE FROM [Posts] WHERE [PostId] = 2

  After SaveChanges:
    Blog '1' is in state Unchanged with 2 posts referenced.
      Post '1' is in state Detached with FK '1' and no reference to a blog.
      Post '2' is in state Detached with FK '1' and no reference to a blog.
```

This is output from the following code snippet where the `Blog` and `Post` entity have a one to many required relationship defined with the default `DeleteBehavior` of `Cascade`.

```
var blog = context.Blogs.Include(b => b.Posts).First();
var posts = blog.Posts.ToList();

DumpEntities("  After loading entities:", context, blog, posts);

blog.Posts.Clear();

DumpEntities("  After making posts orphans:", context, blog, posts);

try
{
    Console.WriteLine();
    Console.WriteLine("  Saving changes:");

    context.SaveChanges();

    DumpSql();

    DumpEntities("  After SaveChanges:", context, blog, posts);
}
catch (Exception e)
{
    DumpSql();

    Console.WriteLine();
    Console.WriteLine($"  SaveChanges threw {e.GetType().Name}: {(e is DbUpdateException ? e.InnerException.Message : e.Message)}");
}
```

In a default or optional relationship, with **DeleteBehavior.Cascade** (default), executing `blog.Posts.Clear()` the `Blog` entity will have no posts referenced. After calling `context.SaveChanges()` the `Blog` entity will have no posts referenced.

The following text corrections should be made.

The line `Blog '1' is in state Unchanged with 2 posts referenced.` under `After SaveChanges:` should instead state `Blog '1' is in state Unchanged with no posts referenced.`

The line `Blog '1' is in state Unchanged with 2 posts referenced.` under the line `After making posts orphans:` should become `Blog '1' is in state Unchanged with no posts referenced.`

The entire correct output would be the follow.

```
After loading entities:
    Blog '1' is in state Unchanged with 2 posts referenced.
      Post '1' is in state Unchanged with FK '1' and reference to blog '1'.
      Post '2' is in state Unchanged with FK '1' and reference to blog '1'.

  After making posts orphans:
    Blog '1' is in state Unchanged with no posts referenced.
      Post '1' is in state Modified with FK '1' and no reference to a blog.
      Post '2' is in state Modified with FK '1' and no reference to a blog.

  Saving changes:
    DELETE FROM [Posts] WHERE [PostId] = 1
    DELETE FROM [Posts] WHERE [PostId] = 2

  After SaveChanges:
    Blog '1' is in state Unchanged with no posts referenced.
      Post '1' is in state Detached with FK '1' and no reference to a blog.
      Post '2' is in state Detached with FK '1' and no reference to a blog.
```

It also seems the following sections exhibit the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 18:31
Duplicate of #473

**Closed by ajcvickers** 2019-09-02 18:31 UTC
