### ISSUE TITLE
Consider re-adding wwwroot/lib folders in our ASP.NET Core samples

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1024] opened 2018-10-04 02:07 UTC
We have an entry in .gitignore (@AndriySvyryd, you apparently added as part of https://github.com/aspnet/EntityFramework.Docs/pull/628/files) that prevents these folders from being committed, but the experience of running the samples without the lib directories is poor, for example:

![image](https://user-images.githubusercontent.com/1253414/46449111-0d9c1500-c73f-11e8-8527-3665d2b38fe3.png)

vs.

![image](https://user-images.githubusercontent.com/1253414/46449087-f52bfa80-c73e-11e8-8178-9d1622464bcf.png)

And 

![image](https://user-images.githubusercontent.com/1253414/46449120-1856aa00-c73f-11e8-8938-614a176e5dd1.png)

vs.

![image](https://user-images.githubusercontent.com/1253414/46449098-fc530880-c73e-11e8-9cff-6301425679d3.png)

**Comment by ajcvickers** [comment] 2019-09-02 19:37
Duplicate of $481

**Closed by ajcvickers** 2019-09-02 19:37 UTC
Labels: area-getting-started, type-enhancement
