### ISSUE TITLE
SQLite: Issue in finding the database

### ISSUE THREAD

**Issue by AvinavaBasu** [aspnet/EntityFramework.Docs#1225] opened 2019-01-09 11:51 UTC
When we run the application, Sqlite threw exception of not finding 'Blogs' table.
This post helped resolve that,
https://stackoverflow.com/questions/33455041/asp-net-5-ef-7-and-sqlite-sqlite-error-1-no-such-table-blog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-01-09 19:49
Thanks for bringing this to our attention. cc @tdykstra 	- see Nates comments in SO.

**Comment by tdykstra** [comment] 2019-01-11 21:21
@AvinavaBasu What OS are you running on? I just ran through the tutorial on Windows and could not reproduce the error.

The SO post referenced appears to be out of date.  Using just the db filename in the connection string, the system uses the file in the project folder for both design and runtime.  It doesn't create a file in the bin/debug/netcoreappx.x folder.  This connection string also works correctly when you deploy to Azure App Service.

**Comment by Rick-Anderson** [comment] 2019-01-11 21:38
24.5K PV/month, 94% CSAT

**Comment by A143730** [comment] 2019-01-14 05:56
I am using IDesignTimeDbContextFactory to create the database and using Add-Migration InitialCreate. This requires me to implement CreateDbContext method in context factory. 
 public DemoContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<DemoContextContext>();
            optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=DemoDb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
            return new DemoContext(optionsBuilder.Options);
        }

Here, is there any way i can read the connection string from appsettings.json rather than hardcoding it in the method?

**Comment by AvinavaBasu** [comment] 2019-01-14 11:04
I am using Windows 10, that shouldn't be a problem.

**Comment by tdykstra** [comment] 2019-01-14 16:20
@AvinavaBasu Then the tutorial instructions should work; do you remember if you did anything different from the steps in the tutorial?

**Comment by AvinavaBasu** [comment] 2019-01-14 16:24
Nope i did exactly as was instructed there, however i ran into the problem
as mentioned.
Anyways i will try running it again, and see if i can reproduce the issue.I
will update you accordingly.

**Comment by ajcvickers** [comment] 2019-09-01 18:28
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 18:28 UTC
