### ISSUE TITLE
There is no Migrate method.

### ISSUE THREAD

**Issue by sbeaudoin** [aspnet/EntityFramework.Docs#1275] opened 2019-02-09 14:39 UTC
Using Microsoft.EntityFrameworkCore.SQLite nuget v2.2.1 on a .Net Standard 2.0 project you reference as the "data model" project.  It contains a class called "DataContext" who inherits the dbContext class.  Successfully create the initial migration.  In my UWP application, in the constructor of app.xaml.cs, I create an instance of my "DataContext" class, assign it to the db variable and call "db.Database.Migrate()".  A CS1061 error indicates (translated) "'DatabaseFacade' does not contain a definition for 'Migrate'".  Suspecting that a partial class should have been created with this method somewhere during the initial migration, I searched the whole solution for a migrate method and could not find any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by sbeaudoin** [comment] 2019-02-09 14:50
Got it...  I did not typed the "using Microsoft.EntityFrameworkCore;" in the app.xaml class.  I suggest to accentuate the need for it.

**Comment by ajcvickers** [comment] 2019-09-01 19:11
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 19:11 UTC
