### ISSUE TITLE
EF Core: update the documenation on how to write a provider

### ISSUE THREAD

**Issue by spatialbridge** [aspnet/EntityFramework.Docs#847] opened 2018-07-18 14:56 UTC
Hi, I'm trying to get my head around writing a custom EF Core provider. I'm looking at the EF Core codebase and the blog post by Arthur Vickers as suggested. However, I don't see the correlation between the blog post and the codebase. 

For example, the first step in the blog indicates to implement IDatabaseProviderServices. However, a search of the solution yields no results for IDatabaseProviderServices.

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a5729-3ab9-2d56-fabb-678256cfc5e1
* Version Independent ID: 0c546b6d-05b6-6f6f-3ad7-f31380d4562a
* Content: [Writing a Database Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/writing-a-provider#feedback)
* Content Source: [entity-framework/core/providers/writing-a-provider.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/writing-a-provider.md)
* Product: **entity-framework**
* GitHub Login: @anmiller
* Microsoft Alias: **divega**

**Comment by MisinformedDNA** [comment] 2018-07-18 20:40
I think Arthur's post is from EFCore 1.X, because I have also found no existence of any DatabaseProviderServices.

Looking at code is probably the way to go now. I'm going to try and follow the step by step creation of the [Cosmos DB provider](https://github.com/aspnet/EntityFrameworkCore/issues/8443).

Out of curiosity, for what database are you writing a provider? I was looking at doing Azure Table Storage.

**Comment by ErikEJ** [comment] 2018-07-18 20:56
Please notice there are big differences between writing a Relational provider and a non-relational provider. I am in the process of writing a Relational provider, and you may find the commit story and currently tiny provider codebase helpful. The provider does not currently implement Migrations or Scaffolding or Model extensions, which helps keeping it small, but it can create databases and tables and run queries against Northwind.

**Comment by spatialbridge** [comment] 2018-07-19 12:12
@MisinformedDNA Thanks, Dan. I'll take a look at it.

**Comment by spatialbridge** [comment] 2018-07-19 12:13
@ErikEJ Hi Erik. Yes, I'm looking to implement a relational provider. Just the basics such as you've implemented so far will be good enough to get me started. Which project should I be looking at?

**Comment by ErikEJ** [comment] 2018-07-20 00:50
This one https://github.com/GibraltarSoftware/VistaDB.EFCore (develop branch)

**Comment by spatialbridge** [comment] 2018-07-20 09:44
Excellent! Thank you, @ErikEJ.

**Comment by MisinformedDNA** [comment] 2018-07-20 14:23
Back to the OP, the documentation needs to be updated to either not mention @ajcvickers post, or add a note of caution that it's for an old, incompatible version.

**Comment by ajcvickers** [comment] 2018-07-25 16:54
@MisinformedDNA Updating the docs is on my list, but unfortunately not very near the top. I will get to it as soon as I can.

**Comment by divega** [comment] 2018-08-01 00:47
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/681.

**Closed** 2018-08-06 18:59 UTC

**Comment by balukantu** [comment] 2019-12-23 07:38
Hi Team, 

I am working on a service fabric project and the data is stored in a reliable collection (in memory).
I am planning to write a custom EF Core provider to do CRUD operations in Reliable collections. 

Can you provide me the basic steps to create a custom provider?

**Comment by ajcvickers** [comment] 2019-12-26 20:08
@balukantu This is tracked by #681
