### ISSUE TITLE
Separate Migrations Project Breaks Add > New Scaffolded Item... for Razor Pages using Entity Framework (CRUD)

### ISSUE THREAD

**Issue by CNHume** [aspnet/EntityFramework.Docs#2013] opened 2019-12-30 23:56 UTC
I can move my Migrations and the Models into a separate "Migrations Project", configuring this project for the DbContext by specifying the MigrationsAssembly() action.

Migrations appear to be set up correctly after this.  However, the Add &gt; New Scaffolded Item... no longer works for Razor Pages using Entity Framework (CRUD).

An Error dialog appears with the message "There was an error running the selected code generator:
'Sequence contains no matching element'"

Is there something more to be done that will allow New Scaffolded Item... to find the models in the Migration Project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545eeff-6c33-3cc0-09ce-a3ad342d7438
* Version Independent ID: 34bc1bac-7338-d8ab-390d-8c5e88a48c10
* Content: [Using a Separate Migrations Project - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/projects?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/projects.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/projects.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by CNHume** [comment] 2019-12-31 00:13
To be clear.  My objective is to have three Projects: 

An ASP.Net Core Web API
An ASP.Net Web Application (using Razor MVVM Pages)
A project the first two can share for their Migrations and Models

I can successfully set up the Migrations and Models Project (though the rough outline given here could really stand some improvement).

However, the New Scaffolded Item... wizards cease to work given this project configuration.

I suspect they are unable to find the Models (despite these being listed in the Entity Framework drop-down, along with the DbContext.)

**Comment by CNHume** [comment] 2019-12-31 23:56
Found the cause of this problem.  Somewhere along the line, I had decided to upgrade the Microsoft.VisualStudio.Web.CodeGeneration.Design Package to the "Latest Stable Version" of 3.1.0.

The Entity Framework based Add > New Scaffolded Item... wizards to not work in this version.  The fix was to revert to:
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />

**Comment by CNHume** [comment] 2019-12-31 23:56
The fix was to revert to Version 3.0.0.

**Comment by ajcvickers** [comment] 2020-01-02 21:13
Duplicate of external issue: https://github.com/aspnet/Scaffolding/issues/1185

**Closed by ajcvickers** 2020-01-02 21:13 UTC
