### ISSUE TITLE
Update for 2.1 through 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/EntityFramework.Docs#1521] opened 2019-06-14 16:20 UTC
>The tools first try to obtain the service provider by invoking Program.BuildWebHost() and accessing the IWebHost.Services property.

The method names for 2.1-3.0 are Program.CreateWebHostBuilder and Program.CreateHostBuilder.

Related to #1465 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa64390-1232-8dd3-f170-7d5c68e29ad9
* Version Independent ID: 245bbba8-3102-4a66-15eb-650e05eb9e62
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation)
* Content Source: [entity-framework/core/miscellaneous/cli/dbcontext-creation.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dbcontext-creation.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2019-06-14 21:16
Also mentioned in #1087

**Comment by ajcvickers** [comment] 2019-09-02 17:51
Duplicate of #1464

**Closed by ajcvickers** 2019-09-02 17:51 UTC
