### ISSUE TITLE
Make a warning about eager loading causing System.Text.Json.JsonExceptions 

### ISSUE THREAD

**Issue by libertizer** [aspnet/EntityFramework.Docs#2112] opened 2020-02-14 08:10 UTC
Since Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance EVEN IF WE DONT EXPLICITLY INCLUDE THE DATA (!), System.Text.Json.JsonExceptions can occur due to  possible object cycles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-02-15 00:31
Duplicate of https://github.com/dotnet/efcore/issues/19910

**Closed by ajcvickers** 2020-02-15 00:31 UTC
