### ISSUE TITLE
Ambient transactions

### ISSUE THREAD

**Issue by Meertman** [aspnet/EntityFramework.Docs#1094] opened 2018-11-02 14:06 UTC
Hi,

Based on the example of ambient transactions, I tried to implement this functionality for two different contexts, but using the same connection string. However, when executing the code, I received the error: "This platform does not support distributed transactions."

After some searching, I found both the following github post, as well as a blog via ThinkTecture that both stated that distributed transactions were not supported using EF.Core. (https://weblogs.thinktecture.com/pawel/2018/06/entity-framework-core-use-transactionscope-with-caution.html, https://github.com/dotnet/corefx/issues/29633)

Is the documentation out-of-date, or is there some information that I am missing?

Kind regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 876c88d4-2972-d905-28d7-56f9e589f309
* Version Independent ID: 29002343-fa42-2f49-3362-53592039b26d
* Content: [Connection Resiliency - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)
* Content Source: [entity-framework/core/miscellaneous/connection-resiliency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-resiliency.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment] 2018-11-02 20:08
@Meertman thanks for reporting this. This is a limitation of System.Transactions in .NET Core, not a limitation of EF Core. If you use EF Core on .NET Framework, the implementation of System.Transactions there does support distributed transactions. That is what "platform" is referring to in the exception you saw. 

The limitation is tracked at https://github.com/dotnet/corefx/issues/13532. I encourage you to add information about why you need this and to up-vote that issue. 

In the meantime, a workaround that may or may not apply to your case, is to share the connection object between the two DbContext instances. Of course, you can only do this if they are both actually connecting to the same database. 

@AndriySvyryd I believe we should have clarified that distributed transactions only work in .NET Framework at the moment in the ambient transaction example. Am I missing anything?

**Comment by AndriySvyryd** [comment] 2018-11-02 20:41
@divega correct

**Comment by Meertman** [comment] 2018-11-05 10:48
@divega, thanks for the reaction. I already came across the issue on GitHub as well and based on your suggestion have upvoted it.

Another question I have regarding this (if you want I can create a second comment), is how to deal with two different contexts and a retry strategy. In the example using the database transaction, you use the first context ('db') for creating a strategy. But in the strategy you use a second context ('context') for making changes to the database. 

Should this not be the same context? e.g.

using (var db = new BloggingContext())
{
    var strategy = db.Database.CreateExecutionStrategy();

    strategy.Execute(() =>
    {
        using (var transaction = db.Database.BeginTransaction())
        {
            db.Blogs.Add(new Blog {Url = "http://blogs.msdn.com/dotnet"});
            db.SaveChanges();

            db.Blogs.Add(new Blog {Url = "http://blogs.msdn.com/visualstudio"});
            db.SaveChanges();

            transaction.Commit();
        }
    });
}

And if so, how would this work with multiple (different) contexts? (I see that a strategy has ExecutionStrategyDependencies and I assume that these should then contain dependencies from both contexts?)

**Comment by ajcvickers** [comment] 2019-08-29 21:59
Duplicate of #906

**Closed by ajcvickers** 2019-08-29 21:59 UTC

**Comment by dwcy** [comment] 2025-06-24 12:58
var dbcont = ContextFactory.CreateDbContext();
			dbcont.set<TEntity>();
			_ = operation switch
			{
				DbOperation.Add => set!.Add(entity),
				DbOperation.Update => set!.Update(entity),
				DbOperation.Remove => set!.Remove(entity),
				_ => throw new ArgumentOutOfRangeException(nameof(operation), $"Unsupported DB operation: {operation}")
			};

			await dbcont!.SaveChangesAsync(cancellationToken); what is wrong?
