### ISSUE TITLE
Rationalize list of additional tutorials 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1499] opened 2019-05-31 22:20 UTC
From discussion in https://github.com/aspnet/EntityFramework.Docs/pull/1475, figure out what to do with list of additional ASP.NET Core tutorials at the bottom of some of ours:

- Should it be the same at the bottom of all ASP.NET Core-related tutorials? 
- Should it be a single link? 
- Should it be moved to the ToC as external links?

**Comment by ajcvickers** [comment] 2019-09-02 17:38
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 17:38 UTC
