### ISSUE TITLE
EnlistTransaction does not exist in EF 2.0

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/EntityFramework.Docs#1622] opened 2019-08-04 02:33 UTC
https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/Transactions/CommitableTransaction/Sample.cs#L37
```
context.Database.EnlistTransaction(transaction);
```

EnlistTransaction  was added in 2.1 https://github.com/aspnet/EntityFrameworkCore/issues/5595

So this stops the samples from compiling for me. any ideas why it doesnt break other people?

**Comment by ajcvickers** [comment] 2019-09-02 18:38
EF Core 2.0 and lower are out-of-support, so closing docs issues specific to these releases.

**Closed by ajcvickers** 2019-09-02 18:38 UTC

**Comment by SimonCropp** [comment] 2019-09-02 22:07
This wasnt about v2. It was about not being able to build the current version of docs

**Comment by ajcvickers** [comment] 2019-09-02 22:11
@SimonCropp My mistake. Duplicate of #1074

**Comment by SimonCropp** [comment] 2019-09-02 22:12
Cool. Thanks for the forward
