### ISSUE TITLE
Keeps using InitialCreate

### ISSUE THREAD

**Issue by henryjones000** [aspnet/EntityFramework.Docs#1940] opened 2019-11-22 06:07 UTC
I made two migrations, InitialCreate then Rating.
When I use Update-Database, it keeps executing InitialCreate! Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment] 2019-11-24 22:56
@henryjones000 This should not be happening. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment] 2019-12-02 17:53
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-12-02 17:53 UTC
