### ISSUE TITLE
Should mention that you need to add a reference to Microsoft.EntityFrameworkCore.Relational for ToView() to be found

### ISSUE THREAD

**Issue by IanKemp** [aspnet/EntityFramework.Docs#1679] opened 2019-08-29 08:39 UTC
I spent about half an hour digging around trying to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 19:15
Duplicate of #740

**Closed by ajcvickers** 2019-09-02 19:15 UTC
