### ISSUE TITLE
Document notification entities, including expectation for timing of Changing/Changed notification

### ISSUE THREAD

**Issue by sjb-sjb** [aspnet/EntityFramework.Docs#1022] opened 2018-10-03 22:54 UTC
The only document I have found on notification entities is in a blog, https://blog.oneunicorn.com/2016/11/16/notification-entities-in-ef-core-1-1 … a search for "notification" in aspnet / EntityFramework.Docs didn't turn up much. This is a topic that deserves documentation.

In particular, what are the expectations for timing of PropertyChanged notifications? I notified PropertyChanged for a store-generated principle key (Id) asynchronously after SaveChanges had returned, and I received an exception from EF. The exception said "The property 'Id' on entity type X is part of a key and so cannot be modified or marked as modified. […]".  However, the modification was done by EF i.e. when storing the store-generated key, not by my code. It would seem that the delayed notification of Id (after completion of SaveChanges) was triggering EF to try to mark the Id field as modified.

**Comment by ajcvickers** [comment] 2019-08-29 21:10
Duplicate of #531

**Closed by ajcvickers** 2019-08-29 21:10 UTC
