### ISSUE TITLE
A "Multiple Models Targeting the Same Database" sample would be helpful

### ISSUE THREAD

**Issue by RichardJFoster** [aspnet/EntityFramework.Docs#1014] opened 2018-10-02 12:38 UTC
As currently written, the information on supporting multiple models within a single database is quite limited. A sample showing the "how" in more detail would be appreciated, along with any applicable commentary on the "why".

For example, in our case we want/need to support a "plug-in" style architecture for a core product to better support independent development of functionality associated with related products. The multiple models, same database option is likely to be the one that will cause least problems for our customers.

Other options we are considering include:

* A separate database instance for each optional module. This would introduce a potential additional point of failure for each add-in as the majority will be pulling information from at least two DB contexts - specifically the core context and their own. It also introduces more complexity for the end-customer as they (or their IT department) would need to understand which instances are in use for which product module(s).

* A single all-encompassing context containing the superset of both core and optional modules. This option raises multiple concerns. a) The data store will contain empty tables for modules that are not in use. b) If a schema change is necessary, it would only be possible to accomplish by updating all active add-in modules to compatible versions at the same time even if the change was only needed for a single add-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/index#multiple)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-08-29 20:50
Duplicate of #750

**Closed by ajcvickers** 2019-08-29 20:50 UTC
