### ISSUE TITLE
Document implementation of INotifyPropertyChanged/INotifyPropertyChanging after reverse engineering?

### ISSUE THREAD

**Issue by Moorepheus** [aspnet/EntityFramework.Docs#1144] opened 2018-11-29 18:00 UTC
Are there any plans to add the ability to implement INotifyPropertyChanged/INotifyPropertyChanging to the scaffolding process?   Right now, if I want to do this, I have to manually update all the models, which, in turn, will not allow me to re-run the scaffolding process in the future if I need to make changes.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ErikEJ** [comment] 2018-11-29 18:02
You could maybe use EF Core Power Tools with Handlebars or the Handlebars NuGet extension with the command line scaffolding?

**Comment by Moorepheus** [comment] 2019-03-11 19:16
Thanks for the feedback... We are having issues with even get dotnet ef dbcontext scaffold to work in CLI.  Keep getting circular dependency in the target dependency involving "GETEFProjectMetadata".  This is in a clean .Net WinForm project.  Nothing has been added except the nuket packages for EFCore 2.2.2

**Comment by smitpatel** [comment] 2019-09-21 01:20
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/4038

**Closed by smitpatel** 2019-09-21 01:20 UTC
Labels: area-scaffolding, type-enhancement
