### ISSUE TITLE
Instructions Do Not Work for EF Core 2

### ISSUE THREAD

**Issue by markolbert** [aspnet/EntityFramework.Docs#1670] opened 2019-08-25 01:24 UTC
I get so sick and tired of Microsoft not bothering to keep their documentation synchronized with the current environment. I am trying to configure my VS2019 environment so I can do a simple "dotnet ef migrations add..." command -- and am running into failure after failure, despite following the directions on this page (for EF Core 2). The design package was added to the csproj file, I'm in the correct directory within the package manager console...and yet the command "dotnet ef", which should list available commands, pukes up an error that the specified file cannot be found. Really? Thanx, that's very helpful for figuring out what's wrong!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by markolbert** [comment] 2019-08-25 01:42
Some further information...

This is apparently a known problem whenever you install Net Core 3 preview. It's been discussed over on github extensively, with a variety of workarounds offered. 

The one I used -- because I'm not currently developing Core 3 apps, I just installed the SDK to experiment/play around with it -- is this:

dotnet tool uninstall --global dotnet-ef
dotnet tool install --global dotnet-ef --version 2.1.0

in the package manager console. The first command uninstalls your current version of the tooling -- which, if like me, you just used the defaults is apparently 2.2+, which will not work properly when Core 3 preview is installed -- while the second installs a downrev version which works. Ghu only knows what functionality you may lose by using an older version, but that's Microsoft for you these days: keep churning away and don't bother to keep developers from running head-on into walls that shouldn't be there.

**Comment by ajcvickers** [comment] 2019-09-02 19:08
Duplicate of #1588

**Closed by ajcvickers** 2019-09-02 19:08 UTC
