### ISSUE TITLE
3.0 Changed AsNoTracking identity resolution

### ISSUE THREAD

**Issue by joelweiss** [aspnet/EntityFramework.Docs#1814] opened 2019-10-04 18:30 UTC
According to the [Breaking Change Doc](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#notrackingresolution)

the following is no longer true

> No tracking queries still perform identity resolution within the executing query. If the result set contains the same entity multiple times, the same instance of the entity class will be returned for each occurrence in the result set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment] 2019-10-04 22:22
Duplicate of #1412 
On my radar to update soon.

**Closed by smitpatel** 2019-10-04 22:22 UTC

**Comment by joelweiss** [comment] 2019-10-06 09:16
@smitpatel #1412 seems like it is about a change in the tracking of Query types.

**Comment by smitpatel** [comment] 2019-10-07 19:07
@joelweiss - It is about all related changes around tracking in 3.0. Like tracking when doing client eval etc. I will update it all.
