### ISSUE TITLE
generate views

### ISSUE THREAD

**Issue by gzinger** [aspnet/EntityFramework.Docs#1313] opened 2019-02-26 22:46 UTC
Is there way to reverse engineer views to models?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by jahbenjah** [comment] 2019-02-27 17:39
Actually,  Reverse engineering Views is a manual process.
"From the Ef Core RoadMap Reverse engineering database views into query types (#1679): In EF Core 2.1, we added support for query types, which can represent data that can be read from the database, but cannot be updated. Query types are a great fit for mapping database views, so in EF Core 3.0, we would like to automate the creation of query types for database views."

**Comment by bricelam** [comment] 2019-02-27 22:45
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/1679

**Closed by bricelam** 2019-02-27 22:45 UTC
