### ISSUE TITLE
I made a small change on the db Script, title column is Varchar(50) instead of Varchar(max)

### ISSUE THREAD

**Issue by PeterLuZC** [aspnet/EntityFramework.Docs#1405] opened 2019-04-02 20:38 UTC
but, the model class it generated does not have the attribute like  [StringLength(59)]

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1601c3e-3f29-5d84-6350-2b38eeaf6adc
* Version Independent ID: 92a856d6-c5da-e215-46ac-d67c411f3ff9
* Content: [Reverse Engineering - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding)
* Content Source: [entity-framework/core/managing-schemas/scaffolding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/scaffolding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment] 2019-04-04 04:02
What version are you using? What database provider?

**Comment by bricelam** [comment] 2019-04-04 04:04
Does OnModelCreating contain HasColumnType(“varchar(50)”) ?

**Comment by ajcvickers** [comment] 2019-09-02 16:30
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-09-02 16:30 UTC
