### ISSUE TITLE
State change events

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/EntityFramework.Docs#849] opened 2018-07-19 11:21 UTC
You guys really need to write more about how to use the: State change events
It is really a much needed feature that completes the override savechanges method. With State change events it has become possible to intercept all CRUD related queries 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d786fb-de7d-de13-7989-c29bfb990e4f
* Version Independent ID: 2f981058-e284-cb85-574c-a2cade3f2174
* Content: [What is new in EF Core 2.1 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.1)
* Content Source: [entity-framework/core/what-is-new/ef-core-2.1.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-2.1.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment] 2018-08-01 00:48
Duplicate of https://github.com/aspnet/EntityFramework.Docs/issues/661.

**Closed** 2018-08-06 18:59 UTC
