### ISSUE TITLE
Migration not creating with Startup project if an UWP project already exists

### ISSUE THREAD

**Issue by Mehigh17** [aspnet/EntityFramework.Docs#1302] opened 2019-02-22 00:15 UTC
**Issue:** If you already have an existing UWP project in the solution and create a dummy startup project to ensure the migrations tools work, you will get a referencing error where it tells you that the dummy startup project should reference the UWP project too besides the Model project.

**Solution:** Remove the UWP project from the solution *(you don't need to remove the entire project folder)*. Once you've done that the migration tooling now works. Once you get the migrations add back the UWP project to the solution.

**Additional Info**: This is the error you get when the UWP project isn't referenced but exists in the solution: `Could not load assembly 'ProjectName.UWP'. Ensure it is referenced by the startup project 'ProjectName.Startup'.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-01 19:40
Duplicate of #481

**Closed by ajcvickers** 2019-09-01 19:40 UTC
