### ISSUE TITLE
Lazy Loading Proxies - `new` limitation not mentioned earlier

### ISSUE THREAD

**Issue by kylejrp** [aspnet/EntityFramework.Docs#1553] opened 2019-07-05 16:08 UTC
In the "Lazy Loading without proxies" section, we have:

> ...allows entity instances created with `new` to lazy-load once attached to a context

However, this limitation isn't mentioned in the earlier section that talks about Lazy Loading with proxies. I'm also not sure what this limitation actually is in the context of Lazy Loading with proxies - maybe an example would be helpful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by IAmHopp** [comment] 2019-07-22 18:03
> I'm also not sure what this limitation actually is in the context of Lazy Loading with proxies - maybe an example would be helpful?

Strongly agree here.

**Comment by ajcvickers** [comment] 2019-09-02 18:06
Duplicate of #1220

**Closed by ajcvickers** 2019-09-02 18:06 UTC
