### ISSUE TITLE
Issue with code example for handling deletes with disconnected entities and auto-generated keys

### ISSUE THREAD

**Issue by iokill** [aspnet/EntityFramework.Docs#1650] opened 2019-08-19 10:09 UTC
Hi!

To properly handle mixed adds, updates and deletes of related entities, I use the same logic as shown in the example here: https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#handling-deletes

I however noticed that there is an issue with this code when its used in combination with auto-generated keys: As soon as more than one new entity is added, the code does only add the last of them.

Here's an example of what I mean: Let's assume we previously inserted this `Blog` and related `Posts` entities:

```csharp
var blog = new Blog
{
    Url = "http://sample.com",
    Posts = new List<Post>
    {
        new Post {Title = "Post 1"},
        new Post {Title = "Post 2"},
    }
};
```

Let's say, with auto-generated keys, `Blog` gets `Id = 1`, and the two related `Post` entities get `Id = 1` and `Id = 2`, respectively.

We then create the following disconnected entity and call `InsertUpdateOrDeleteGraph()` (from the docs):

```csharp
var blog = new Blog
{
    Id = 1,
    Url = "http://sample-new.com",
    Posts = new List<Post>
    {
        new Post {Id = 1, Title = "Updated Post 1"},
        new Post {Title = "New Post 2"},
        new Post {Title = "New Post 3"},
    }
};

InsertUpdateOrDeleteGraph(ctx, blog);
```

This will do everything we expect, **except** insert `new Post {Title = "New Post 2"}`!

The issue is in the first `foreach` loop where we do

```csharp
var existingPost = existingBlog.Posts
                .FirstOrDefault(p => p.PostId == post.PostId);

if (existingPost == null)
{
    existingBlog.Posts.Add(post);
}
else
{
    context.Entry(existingPost).CurrentValues.SetValues(post);
}
```

Since both new `Post` entities have the same value for `Id` (`default(int)`), we'll end up just replacing the property values of the first new `Post` with the last one in the list.

I'd suggest to add a note that either the example code is only intended when no auto-generated keys are used, or fix the code accordingly.

Thanks!

**Comment by ajcvickers** [comment] 2019-09-02 18:54
Duplicate of #1489

**Closed by ajcvickers** 2019-09-02 18:54 UTC
