### ISSUE TITLE
Ignoring concurrency check

### ISSUE THREAD

**Issue by mogaozq** [aspnet/EntityFramework.Docs#1287] opened 2019-02-15 15:04 UTC
Given i have set a concurrency token for an entity. In some cases (database commands) i don't matter the concurrency, i just want SQL commands to be executed without checking for concurrency token.
So, how can i Ignore concurrency check for special database operations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency#feedback)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by MarTeezy** [comment] 2019-03-14 18:31
I am also working on this issue. Our solution is to enable OCC `OnModelCreating` in EFCore. We have a background worker we want to ignore OCC, so we don't enable the check on that DbContext object.

**Comment by ajcvickers** [comment] 2019-09-01 19:14
Duplicate of issue https://github.com/aspnet/EntityFrameworkCore/issues/10443

Leaving open to consider documenting workaround.

**Comment by divega** [comment] 2019-09-11 17:48
Triage: We don't believe we should recommend the workaround described above. For now it is just a missing feature. If someone comes with another workaround we can consider it.

**Closed by divega** 2019-09-11 17:48 UTC
Labels: area-optimistic-concurrency, type-enhancement

**Comment by santosh-kh** [comment] 2020-04-17 11:47
Any suggestible work around?

**Comment by ajcvickers** [comment] 2020-04-17 15:24
@santosh-kh Try implementing an `IDbCommandInterceptor` to manipulate the return value representing the number of rows affected.
