### ISSUE TITLE
Seeding user

### ISSUE THREAD

**Issue by Scandal-UK** [aspnet/EntityFramework.Docs#730] opened 2018-06-01 11:22 UTC
How is the initial ASP.NET Identity user seeded? Is it similar? What about claims?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by Ciwan1859** [comment] 2018-06-10 14:59
I too would like to know how to seed a user in EF Core 2.1.0.

**Comment by ajcvickers** [comment] 2018-06-11 17:32
Duplicate of #736

**Closed by ajcvickers** 2018-06-11 17:32 UTC
