### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by lebartha** [aspnet/EntityFramework.Docs#2028] opened 2020-01-06 16:23 UTC
Well it has been what a month almost and the docs have not been updated? Holidays or not, it should have been updated on day 1 when 3.1 was released...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ec70a8-5402-78da-2a4d-c3d2c1e59f97
* Version Independent ID: da449417-8152-ce2d-4aec-fbd9b692e432
* Content: [What's new - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/#feedback)
* Content Source: [entity-framework/core/what-is-new/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment] 2020-01-06 21:43
Duplicate of #1982

**Closed by ajcvickers** 2020-01-06 21:43 UTC
