### ISSUE TITLE
Missing Core documentation

### ISSUE THREAD

**Issue by bendono** [aspnet/EntityFramework.Docs#1229] opened 2019-01-11 07:34 UTC
While there is ASP.NET Core, there is not any general information regarding Dotnet Core. Ideally there should be some discussion for Core console / library projects. In the future, Core WPF will be needed as well, though the details will probably largely overlap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-01 18:35
Duplicate of #876

**Closed by ajcvickers** 2019-09-01 18:35 UTC
