### ISSUE TITLE
About initial migration

### ISSUE THREAD

**Issue by neven10** [aspnet/EntityFramework.Docs#1062] opened 2018-10-19 16:22 UTC
When adding initial migration, InitialCreate -StartupProject Blogging.Migrations.Startup ,
maybe you should hint to set Default project to Blogging.Model in Packet Manager Console.  I though i had messed up references and  working directories. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-08-29 21:35
Duplicate of #933

**Closed by ajcvickers** 2019-08-29 21:35 UTC
