### ISSUE TITLE
Please ignore this for now Will try it later with new dotnet core 

### ISSUE THREAD

**Issue by chicagoairmailcc** [aspnet/EntityFramework.Docs#1659] opened 2019-08-20 21:46 UTC
Measure-Command { dotnet aspnet-codegenerator controller -name BlogsController -m Blog -dc BloggingContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries }

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Web.CodeGeneration.Utils, Version=2.2.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.Main(String[] args)

Days              : 0
Hours             : 0
Minutes           : 4
Seconds           : 30
Milliseconds      : 917
Ticks             : 2709170567
TotalDays         : 0.00313561408217593
TotalHours        : 0.0752547379722222
TotalMinutes      : 4.51528427833333
TotalSeconds      : 270.9170567
TotalMilliseconds : 270917.0567

dotnet --version
2.2.301

used sqlite like in this tutorial :thinking: 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ajcvickers** [comment] 2019-09-02 19:01
Duplicate of #481

**Closed** 2019-09-02 19:00 UTC
