### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Varorbc** [aspnet/EntityFramework.Docs#4186] opened 2022-12-15 07:51 UTC
https://github.com/dotnet/EntityFramework.Docs/blob/bc77922852244e9a3139ec5f278c3f1a10d508b0/samples/core/Miscellaneous/CommandLine/CustomTools.cs#L11

If it is running on the console, the following exception occurs

```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Design.IAnnotationCodeGenerator' while attempting to activate 'Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsCodeGeneratorDependencies'.
```

**Comment by ajcvickers** [comment] 2022-12-15 11:03
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment] 2022-12-17 10:44
Duplicate of #4013.

Try this:

```C#
public class Program
{
    public static void Main()
    {
        AddMigration("InitCreate");

        Console.WriteLine("Hello World");
    }

    public static void AddMigration(string migrationName)
    {
        var projectDir = Directory.GetCurrentDirectory();
        var rootNamespace = "ConsoleApp1";
        var outputDir = "Migraitons";

        #region CustomTools
        var db = new MyDbContext();

        // Create design-time services
        var serviceCollection = new ServiceCollection();
        serviceCollection.AddEntityFrameworkDesignTimeServices();
        serviceCollection.AddDbContextDesignTimeServices(db);

        var provider = db.GetService<IDatabaseProvider>().Name;
        var providerAssembly = Assembly.Load(new AssemblyName(provider));
        var providerServicesAttribute = providerAssembly.GetCustomAttribute<DesignTimeProviderServicesAttribute>();
        var designTimeServicesType = providerAssembly.GetType(providerServicesAttribute.TypeName, throwOnError: true);
        ((IDesignTimeServices)Activator.CreateInstance(designTimeServicesType)!).ConfigureDesignTimeServices(serviceCollection);
        var serviceProvider = serviceCollection.BuildServiceProvider();

        // Add a migration
        var migrationsScaffolder = serviceProvider.GetService<IMigrationsScaffolder>();
        var migration = migrationsScaffolder.ScaffoldMigration(migrationName, rootNamespace);
        migrationsScaffolder.Save(projectDir, migration, outputDir);
        #endregion
    }
}

internal class MyDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite("Data Source=test.db");
}
```

**Comment by ajcvickers** [comment] 2022-12-17 11:01
That's what #4013 is tracking.

**Closed as not planned** 2022-12-19 00:47 UTC
Labels: closed-question

**Comment by svenhue** [comment] 2022-12-29 19:35
Can you please provide information about the dependecies?
I tried this but when i use ServiceCollection from Microsoft.Extensions.DependencyInjection,  there is no definition for AddEntityFrameworkDesignTimeServices and AddDbContextDesignTimeServices.
Also i cant find a definition for IMigrationsScaffolder....

What am i missing? I use ef 6.4

Thanks :)

**Comment by ErikEJ** [comment] 2022-12-29 20:06
EF 6.4 (Classic) does not have these classes. Are you mixing things up?

You need to reference .Design and remove privateAssets in the .csproj.

**Comment by svenhue** [comment] 2022-12-29 20:15
this is my projectfile of the project 
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alpha.Utils.Commands\Alpha.Utils.Commands.csproj" />
    <ProjectReference Include="..\DataCenter.Application.Contracts\DataCenter.Application.Contracts.csproj" />
    <ProjectReference Include="..\DataCenter.Domain\DataCenter.Domain.csproj" />
    <ProjectReference Include="..\DataCenter.Infrastructure\DataCenter.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApplicationServices\BaseServiceClasses\" />
  </ItemGroup>


</Project>
`

and in DataCenter.Infrastructure i have a ref to Design

**Comment by ErikEJ** [comment] 2022-12-29 20:22
I think it would be extremely helpful to share the project with the actual package references...
