### ISSUE TITLE
Clarify when to use "existing database" verses "creating the database"

### ISSUE THREAD

**Issue by ashish2rathi** [aspnet/EntityFramework.Docs#924] opened 2018-08-18 17:09 UTC
Hi, I am new to this scaffolding, the process you are explained is bit confusing in case of creating new database and using existing database. For Creating the Database I think it will be better to create the database and then use it with the given steps. I am not sure that will help or not but I think for new user like me which are using Entity framework very first time, it will reduce the confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by krchome** [comment] 2018-11-26 01:46
I guess it is the wording "Existing Database" that has caused your confusion. Here the words do hold true as the steps above do create a database first by running the scripts. Once the Db is created then it becomes an "existing database" which is used further in the app. 

Alternately the title could be differently stated as "Getting Started with EF Core on ASP.NET Core after creating a database and using it as an existing database" but it is just a re-massaging of words.

**Comment by ajcvickers** [comment] 2019-09-02 19:36
Duplicate of #481

**Closed by ajcvickers** 2019-09-02 19:36 UTC
Labels: area-getting-started, type-enhancement
