### ISSUE TITLE
The documentation sucks

### ISSUE THREAD

**Issue by danrayson** [aspnet/EntityFramework.Docs#1190] opened 2018-12-21 17:22 UTC
This documentation only describes the interface of the method and nothing more.  Not at all useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c4d50d-a88b-36d7-885a-38bb5ff15fad
* Version Independent ID: 7ffdf124-d6ff-401c-3ecf-037b46f7a7a1
* Content: [DbSet&lt;TEntity&gt;.Attach(TEntity) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset-1.attach?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbSet`1.xml)
* Product: **entity-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-01 18:15
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17508

**Closed by ajcvickers** 2019-09-01 18:15 UTC
