### ISSUE TITLE
Raw SQL documentation (FromSql method) doesn't mention the assembly and namespace

### ISSUE THREAD

**Issue by diego-pathmatics** [aspnet/EntityFramework.Docs#1289] opened 2019-02-13 01:16 UTC
Where is `FromSql`? The documentation should mention what assembly, namespace and class contains this method.

**Comment by divega** [comment] 2019-02-22 00:01
As a general approach, we want to cross link to the API documentation when we introduce an extension method (or any other API). We could also consider mentioning the namespaces and assemblies in the conceptual docs, but we want to avoid adding a lot of clutter.

**Comment by ajcvickers** [comment] 2019-09-01 19:36
Duplicate of #740

**Closed** 2019-09-01 19:36 UTC
Labels: good first issue
