### ISSUE TITLE
The term 'Scaffold-DbContext' is not recognized as the  name of a cmdlet

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1684] opened 2019-09-03 07:50 UTC
In Visual Studio 2019 I run the above command in Package Manager Console:

Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

But even when I restart Visual Studio 2019, I get the error message:

Scaffold-DbContext : The term 'Scaffold-DbContext' is not recognized as the 
name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;T ...
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Scaffold-DbContext:String) [],  
   CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Can you please explain how to install Scaffold-DbContext?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Get started on ASP.NET Core - existing database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by pappasa** [comment] 2019-09-03 08:01
I had to run the following two commands:

Install-Package Microsoft.EntityFrameworkCore.Tools
Install-Package Microsoft.EntityFrameworkCore.SqlServer

After that the command Scaffold-DbContext worked ok.

**Comment by Rick-Anderson** [comment] 2019-09-04 15:52
Correct, this tutorial has not been updated yet for 3.0.

**Comment by ajcvickers** [comment] 2019-09-06 19:49
Duplicate of #481

**Closed by ajcvickers** 2019-09-06 19:49 UTC

**Comment by anantyadunath** [comment] 2020-05-01 12:10
This doesnt work for me. I am on v3.1 (Core). Last time I had to use dotnet cli to get this working but does not work in package manager console. 
I already have Tools and SqlServer nuget packages installed.

**Comment by Bychrist** [comment] 2020-05-27 10:43
> Install-Package Microsoft.EntityFrameworkCore.Tools


This worked after i installed it

**Comment by logany-hi** [comment] 2021-05-11 11:03
Unfortunately having pains with the issue now as well. I've installed `Microsoft.EntityFrameworkCore.SqlServer` and `Microsoft.EntityFrameworkCore.Tools` but the Scaffold-DbContext command still returns an error message saying the command is unknown.

    Scaffold-DbContext "Server=redacted;Database=redacted;User Id=redacted;Password=redacted;MultipleActiveResultSets=true" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -t Foo

Unsure how to proceed at this point.

**Comment by Rick-Anderson** [comment] 2021-05-11 17:09
> but the `Scaffold-DbContext` command 
That's not a command.

**Comment by logany-hi** [comment] 2021-05-12 06:18
But...

https://www.entityframeworktutorial.net/efcore/create-model-for-existing-database-in-ef-core.aspx

```
Use Scaffold-DbContext to create a model based on your existing database. The following parameters can be specified with Scaffold-DbContext in Package Manager Console:

Scaffold-DbContext [-Connection] [-Provider] [-OutputDir] [-Context] [-Schemas>] [-Tables>] 
                    [-DataAnnotations] [-Force] [-Project] [-StartupProject] [<CommonParameters>]
In Visual Studio, select menu Tools -> NuGet Package Manger -> Package Manger Console and run the following command:

PM> Scaffold-DbContext "Server=.\SQLExpress;Database=SchoolDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
```

**Comment by Rick-Anderson** [comment] 2021-05-12 16:03
That's not this tutorial.

**Comment by AndriySvyryd** [comment] 2021-05-14 04:20
You can read about `Scaffold-DbContext` on https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=vs
