### ISSUE TITLE
Consider Referencing or Documenting Required Components

### ISSUE THREAD

**Issue by steven-tomlinson** [aspnet/EntityFramework.Docs#1349] opened 2019-03-11 18:03 UTC
This documentation is evolving quite nicely, However, it seems that it would be useful to document the specific libraries or components required to implement the specific functionality.

For example, ion order to use Data Annotations as described above in your Model Definition, you also need to add "using System.ComponentModel.DataAnnotations.Schema;".
The IDE does as very good job of helping you figure this out but it would more helpful when learning, to have that guidance in the documentation, here in the relevant article, where it is easy to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b143a3f-aecb-49b6-66e1-0c459af0e2de
* Version Independent ID: 1b594bfc-f0a3-4938-a415-50ea34805d8e
* Content: [Data Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types)
* Content Source: [entity-framework/core/modeling/relational/data-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/data-types.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-01 21:13
Duplicate of  #729 and #740

**Closed by ajcvickers** 2019-09-01 21:13 UTC
