### ISSUE TITLE
Write a documentation page explaining EF.Functions 

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/EntityFramework.Docs#1676] opened 2019-08-27 08:23 UTC
Write a documentation page explaining EF.Functions 
in https://docs.microsoft.com/en-us/ef/core/querying/

**Comment by xrkolovos** [comment] 2019-08-27 08:57
this is useful 
[](https://entityframework.net/knowledge-base/45708715/entity-framework-ef-functions-like-vs-string-contains)

**Comment by ajcvickers** [comment] 2019-09-02 19:12
Duplicate of #1134

**Closed by ajcvickers** 2019-09-02 19:12 UTC
