### ISSUE TITLE
Update to 3.0: Get started on ASP.NET Core - existing database - EF Core

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1685] opened 2019-09-03 08:54 UTC
In Visual Studio 2019, I create the Controller as shown here: 

https://snipboard.io/yN4puO.jpg .

But when I click on Add, I get the following error:

https://snipboard.io/7bcDTZ.jpg

There was an error running the selected code generator:
'Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublickKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Get started on ASP.NET Core - existing database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by pappasa** [comment] 2019-09-03 09:12
I installed newer tools:

Install-Package Microsoft.EntityFrameworkCore.Tools -version 3.0.0-preview8.19405.11

But upon Add Controller I now get the error:

https://snipboard.io/4Vc6S9.jpg

There was an error running the selected code generator:
'Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtension' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

**Comment by pappasa** [comment] 2019-09-03 09:17
I installed newer SqlServer:

Install-Package Microsoft.EntityFrameworkCore.SqlServer -version 3.0.0-preview8.19405.11

and then Add Controller worked ok.

**Comment by Rick-Anderson** [comment] 2019-09-04 15:49
You're using 3.0 with a 2.1 tutorial.

**Comment by ajcvickers** [comment] 2019-09-06 19:49
Duplicate of #481

**Closed by ajcvickers** 2019-09-06 19:49 UTC
