### ISSUE TITLE
EF Migrarions: How to select the appsettings.env.json for the appropriate database connection string

### ISSUE THREAD

**Issue by fpiazza99** [aspnet/EntityFramework.Docs#1273] opened 2019-02-07 20:07 UTC
We have a Dev, Stage, Prod setup and would like to target only the environment being deployed during a EF Migration/Database-Update/"dotnet ef database update". We store each environments connection string in the environment specific appsettings.ENV.json  config file. So how do we direct "dotnet ef database update" to use a specific environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by eskensberg** [comment] 2019-03-20 13:34
I would also like to know how to update the database with a custom connection string please!

**Comment by bricelam** [comment] 2019-03-20 15:42
``` cmd
set ASPNET_ENVIRONMENT=Stage
dotnet ef database update
```

**Comment by bricelam** [comment] 2019-03-20 17:23
See also https://github.com/aspnet/EntityFrameworkCore/issues/10750

**Comment by christianacca** [comment] 2019-06-07 08:45
Setting the ASPNETCORE_ENVIRONMENT environment variable seems to have no affect for me.

Here's the command I used (in powershell)

``` powershell
$env:ASPNETCORE_ENVIRONMENT='Development'
dotnet ef database update -p FrontEnd.DataAccess -s FrontEnd.Api --no-build
```

**Comment by ajcvickers** [comment] 2019-09-01 19:08
Duplicate of #1050

**Closed by ajcvickers** 2019-09-01 19:08 UTC
