### ISSUE TITLE
Affect on existing state

### ISSUE THREAD

**Issue by SimpleSamples** [aspnet/EntityFramework.Docs#1294] opened 2019-02-18 19:29 UTC
What if the entity is in a changed state? Will this set it to unchanged? In other words, is there ever a need to first check the state before setting it to unchanged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06501e5d-2617-9380-1a99-389a727b3012
* Version Independent ID: db1657b7-d390-7a27-062c-408e166a85ca
* Content: [DbContext.Attach Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.attach?view=efcore-2.1#Microsoft_EntityFrameworkCore_DbContext_Attach__1___0_)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by divega** [comment] 2019-02-21 23:56
@ajcvickers If I remember correctly, the answer is version specific. Is it not?

**Comment by ajcvickers** [comment] 2019-09-01 19:38
Duplicate of #786

**Closed by ajcvickers** 2019-09-01 19:38 UTC
Labels: needs more info
