### ISSUE TITLE
Example calls UseSqlServer, but this article doesn't mention the NuGet package needed

### ISSUE THREAD

**Issue by Dave-Lowndes** [aspnet/EntityFramework.Docs#1508] opened 2019-06-07 11:30 UTC
Although this is a specific example, in general, code snippets on EF Core illustrate methods being called, but fail to mention the NuGet package that's needed. While these requirements may be intuitive to someone deeply familiar with these aspects, they're not to a newcomer, which is particularly relevant for these introductory topics.
I've spent too much frustrating time wondering why some method isn't available to me, only to find it's an extension method that needs some other NuGet package adding to the project.

FWIW, UseSqlServer needs the Microsoft.EntityFrameworkCore.SqlServer NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by softchris** [comment] 2019-06-09 20:20
it does show up in a later page, here https://docs.microsoft.com/en-us/ef/core/get-started/install/. However, I proposed the following change to this page https://github.com/aspnet/EntityFramework.Docs/pull/1514 There is information in there what package you need

**Comment by softchris** [comment] 2019-06-09 20:27
Thinking that IF installation instructions are added here I would recommend how to install SQLServer NuGet as well as the SqlLite one. People might come from both Windows and Mac and might want to see both usages as shown in this article, https://medium.com/@yostane/entity-framework-core-and-sqlite-getting-started-on-macos-and-visual-studio-code-27f3830db77c

If we don't add installation instructions here then maybe a link to installation page would be a nice compromise?

**Comment by Dave-Lowndes** [comment] 2019-06-09 21:42
I think each method should have sufficient information in its own topic for someone to be able to determine where it exists (I'm fairly sure the DLL name was shown), and what's needed to be installed to use it (links to that information are fine). Searching showed me loads of examples using that method, but non that I saw ever mentioned it wasn't in the base component and needed an additional package installing.
As a newcomer to this area, reading even those topics where you rightly say the NuGet package is referenced, before I knew what I now know, I wouldn't have necessarily spotted the information I needed - that's the problem with being new at something. :)

**Comment by ajcvickers** [comment] 2019-09-02 17:40
Duplicate of #740

**Closed by ajcvickers** 2019-09-02 17:40 UTC
