### ISSUE TITLE
Reverse engineering in Linux and MacOS

### ISSUE THREAD

**Issue by hamzatrq** [aspnet/EntityFramework.Docs#392] opened 2017-04-30 12:25 UTC
I am a ubuntu user and trying to reverse engineer a database but because I do not have visual studio I can not run `Scaffold-DbContext` command. Please update this guide to cover other OS.

**Comment by bricelam** [comment] 2017-05-01 15:45
`dotnet ef dbcontext scaffold`

**Comment by ajcvickers** [comment] 2017-06-16 18:50
Make sure that the docs make it clear what works in VS only and what works everywhere.

**Comment by divega** [comment] 2017-12-23 10:01
Closing as duplicate of the main reverse engineering topic, which should cover non-Windows platforms anyway: #508.

**Closed by divega** 2017-12-23 10:01 UTC
Labels: duplicate
