### ISSUE TITLE
Show controller code when getting started with ASP.NET Core

### ISSUE THREAD

**Issue by feload** [aspnet/EntityFramework.Docs#941] opened 2018-08-26 00:04 UTC
It would be great if you guys added an example of the controller code. I wanted to see how the controller was creating a context instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#install-entity-framework-core)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ivanbarrios** [comment] 2018-09-03 16:47
```csharp
private readonly BloggingContext _context;

public BlogsController(BloggingContext context)
{
	_context = context;
}
```

**Comment by ajcvickers** [comment] 2019-09-06 22:21
Dupe of #481

**Closed by ajcvickers** 2019-09-06 22:21 UTC
Labels: area-getting-started, type-enhancement
