### ISSUE TITLE
Indicate where extension methods may require adding a new package reference

### ISSUE THREAD

**Issue by kunom** [aspnet/EntityFramework.Docs#1056] opened 2018-10-15 14:05 UTC
I might be wrong, but `DbContext.Database.UseTransaction(DbTransaction)` does not seem to exist on `DatabaseFacade` (EF Core 2.1.4), and it is not very obvious that there is extension method `RelationalDatabaseFacadeExtensions.UseTransaction`.

Also, maybe, it would be beneficial to mention that the `DbConnection` class is cached inside of the `DbContextOptions` instance via the `RelationalOptionsExtension` class. This was not really obvious to me.

[Update] Finally found out that -- at least for SQLite -- a `DbConnection` instance is only shared if you use the corresponding overload for `SqliteDbContextOptionsBuilderExtensions.UseSqlite`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 19:40
Duplicate of #740

**Closed by ajcvickers** 2019-09-02 19:40 UTC
Labels: area-global, type-enhancement
