### ISSUE TITLE
missing documentation about Unit Tests using a transacion

### ISSUE THREAD

**Issue by JuanZamudioGBM** [aspnet/EntityFramework.Docs#1550] opened 2019-07-02 21:51 UTC
Using this and the InMemory provider generates an error "Relational-specific methods can only be used when the context is using a relational database provider". 
Maybe you can add about how to unit test a method that uses a transaction using something similar to the memory provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#feedback)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 18:03
Duplicate of #837

**Closed by ajcvickers** 2019-09-02 18:03 UTC
