### ISSUE TITLE
Incorrect/misleading documentation regarding uniqueness of HasIndex

### ISSUE THREAD

**Issue by irontoby** [aspnet/EntityFramework.Docs#1319] opened 2019-02-27 20:11 UTC
This documentation states that `HasAlternateKey` will "force the properties to be read-only" and we should "use `HasIndex(Expression<Func<TEntity,Object>>)` to specify uniqueness in the model that does not force properties to be read-only."

However, `HasIndex(Expression<Func<TEntity,Object>>)` does not actually create a unique index; it creates a non-unique index. This sentence should be removed or clarified to indicate whether there's another way to create a unique index which is not read-only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeeaa642-e6b3-e469-f3ba-d57a74770659
* Version Independent ID: 5d69f26b-f6ba-378b-2692-9922c19473e4
* Content: [EntityTypeBuilder&lt;TEntity&gt;.HasAlternateKey(Expression&lt;Func&lt;TEntity,Object&gt;&gt;) Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1.hasalternatekey?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder%601.HasAlternateKey);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder`1.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by irontoby** [comment] 2019-02-27 20:19
My apologies, I just realized that it is indeed possible to create a unique index using `.HasIndex(...).IsUnique()`. Perhaps the documentation could be clarified to mention `IsUnique()`.

**Comment by ajcvickers** [comment] 2019-09-01 20:32
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/17508

**Closed by ajcvickers** 2019-09-01 20:32 UTC
