### ISSUE TITLE
Guidance on how to translate queries

### ISSUE THREAD

**Issue by Danielku15** [aspnet/EntityFramework.Docs#1788] opened 2019-09-30 11:19 UTC
As highlighted in the Limitations section, EF Core might not be able to translate certain queries anymore if there are complex filters in place. In our case we are mapping a `string[]` to a simple CSV `string` on the database. This list is coming from a input control like "chips input" (material design) or special select boxes like select2. It is similar to a tagging system but we would like to avoid introducing for each string-list-property an own "tag" entity hence we map it to a simple CSV (or maybe JSON in future). 

From our API we would like to query if the user entered a certain item for a property. We have an OData API on this data model. The translation of a query like the following obviously is not working by default due to its complexity:

```cs
// http://localhost/odata/posts?$filter=tags/any(t: t in ('Tag1', 'Tag2'))
// class Post { public string[] Tags {get;set;} }
string[] tags = new [] { "Tag1", "Tag2" };
var result = context.Posts.Where(p => p.Tags.Any(t => tags.Contains(t));
```

Lets say for simplicity in a first version we would like to make a simple `Contains()` condition on SQL level. Where could such a translation be done? If we would go for the flat string property and expect the raw CSV on API we would have something like the following: 

```cs
var result = context.Posts.Where(p => p.Tags.Contains("Tag1") || p.Tags.Contains("Tag2") );
```
```sql
SELECT * FROM Posts WHERE (Tags LIKE '%Tag1%' OR Tags LIKE '%Tag2%')
```

In the best case we could specify some special query translator as part of the conversion which allows us to handle certain expressions for the converted property. And this system would need to allow access to the underlying raw value of the database for appropriate translation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment] 2019-10-14 19:31
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/10434

@ajcvickers - What is action item here? We cannot do anything generic here since translation totally depends on ValueConversion. For CSV like works. The syntax would be different from JSON.
User could use UDF to do some custom translation but this would be too specific of a case to write documentation about.

**Closed** 2020-02-10 19:56 UTC
Labels: area-query, type-enhancement
