### ISSUE TITLE
EntityTypeBuilder.HasIndex HasIndex improvement

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/EntityFramework.Docs#4580] opened 2023-12-04 09:19 UTC
I needed to have more than one index on a property, but adding the second index replaced the first. I was told how to achieve this, by using a 2nd `name` argument, but if you don't already know what it does then it is not clear what it is for.

Current text

> Configures an index on the specified properties and with the given name. If there is an existing index on the given list of properties and with the given name, then the existing index will be returned for configuration. This feature allows for the 

Recommended

> Configures an index on the specified properties and with the given name. If there is an existing index on the given list of properties and with the given name, then the existing index will be returned for configuration. This allows the definition of multiple different indexes on the same property, that can be identified by `name`.

Is there a more complete documentation on this somewhere? I was unable to find any MS docs at all explaining how to create multiple indexes on a single property (I have different filters on them). The only doc I found was [this one](https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#:~:text=EF%20Core%20only%20supports%20one%20index%20per%20distinct%20set%20of%20properties.%20If%20you%20configure%20an%20index%20on%20a%20set%20of%20properties%20that%20already%20has%20an%20index%20defined%2C%20either%20by%20convention%20or%20previous%20configuration%2C%20then%20you%20will%20be%20changing%20the%20definition%20of%20that%20index) which talks about only allowing a single index - 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5849407-fc78-90a9-56ad-099df52e7484
* Version Independent ID: 573de756-717a-e546-a153-be1a41f8e3cb
* Content: [EntityTypeBuilder.HasIndex Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.hasindex?view=efcore-7.0#microsoft-entityframeworkcore-metadata-builders-entitytypebuilder-hasindex(system-string()-system-string))
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml](https://github.com/dotnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2023-12-04 10:22
Duplicate of #4582

**Closed as not planned by roji** 2023-12-04 10:22 UTC
Labels: closed-duplicate
