### ISSUE TITLE
Adding an existing related entity

### ISSUE THREAD

**Issue by joeystdio** [aspnet/EntityFramework.Docs#1481] opened 2019-05-22 16:13 UTC
It would be nice to have an example of Adding an existing related entity.
More specifically I am wondering what the correct way is to change a Post's Blog.

So you load an existing Post with its related Blog. Is the correct way to set the BlogId to another Blog, make the Blog property in Post null and then save the Post?

If this is the case, what is, directly after saving the Post, the next step to load the referenced Blog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/related-data#feedback)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment] 2019-09-02 17:26
Duplicate of #1453

**Closed by ajcvickers** 2019-09-02 17:26 UTC
