### ISSUE TITLE
Document what happens on entity state changes

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#852] opened 2018-07-20 23:03 UTC
_From @Wain123 on July 11, 2018 14:29_

When I manually set the state of an entity to Unchanged, the CurrentValues automatically get set to be equal to the OriginalValues. This makes sense but isn't documented in EntityEntry.State metadata.

Are there any other undocumented side effects of setting EntityEntry.State that I might have missed?

_Copied from original issue: aspnet/EntityFrameworkCore#12631_

**Comment by divega** [comment] 2018-07-20 23:03
@Wain123 I cannot think of any other side effects that could be unexpected. I am going to move this issue to our documentation repo so that we can track adding conceptual topics about managing state with these APIs.

**Comment by ajcvickers** [comment] 2019-09-07 20:33
Duplicate of #786

**Closed by ajcvickers** 2019-09-07 20:33 UTC
Labels: area-change-tracking, type-enhancement
