### ISSUE TITLE
Please mention that using IValueConverters for other cases than decimal->double is not for free.

### ISSUE THREAD

**Issue by kunom** [aspnet/EntityFramework.Docs#1590] opened 2019-07-17 10:53 UTC
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

You recommend using a value converter for `decimal` only. I misread this and used it for `DateTime` values. This does not play well with comparisions:

`modelBuilder.Entity<Record>().Property(e => e.Dt3).HasConversion(new DateTimeToTicksConverter());`  and `var tmp2 = db.Records.Where(r => r.Dt3 < DateTime.Now).ToList();` results in 

```
      SELECT "r"."Id", "r"."Dt", "r"."Dt2", "r"."Dt3", "r"."Dto"
      FROM "Records" AS "r"
      WHERE "r"."Dt3" < rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime'), '0'), '.')
```

Not sure whether this is an implementation bug (e.g. as long as converters do not support comparison, this should be evaluated on the client side) or else maybe a documentation bug (the limitations chapter) or else just my lack of understanding.

**Comment by ajcvickers** [comment] 2019-09-02 18:20
Duplicate of #718

**Closed by ajcvickers** 2019-09-02 18:20 UTC
